"""Entity and entity Property and EntityAppointment

Revision ID: 0765eb862cef
Revises: 719dc05fda6f
Create Date: 2024-12-09 23:13:42.650040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0765eb862cef'
down_revision: Union[str, None] = '719dc05fda6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Entity', 'entityPermanentAddressLine2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Entity', 'entityInitialDataReceivedNotes',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Entity', 'entityInitialDataReceivedCheckoutDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Entity', 'entityInitialDataReceivedCheckedOutByID',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('EntityAppointments', 'entityAppointmentsHDBadgeID',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('EntityAppointments', 'entityAppointmentsAppointmentTime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentsSOW',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('EntityAppointments', 'entityAppointmentsNotes',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('EntityProperty', 'entityPropertyAddressLine2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('EntityProperty', 'entityPropertyDirections',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('EntityProperty', 'entityPropertyNotes',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EntityProperty', 'entityPropertyNotes',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('EntityProperty', 'entityPropertyDirections',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('EntityProperty', 'entityPropertyAddressLine2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentsNotes',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentsSOW',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentsAppointmentTime',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentsHDBadgeID',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Entity', 'entityInitialDataReceivedCheckedOutByID',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Entity', 'entityInitialDataReceivedCheckoutDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Entity', 'entityInitialDataReceivedNotes',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('Entity', 'entityPermanentAddressLine2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
