"""deleted SalesJobDocuments, SalesJobDocumentCategory, SalesJobDocumentCategoryDocuments

Revision ID: 0c02e4655cd5
Revises: 2104298d3ac7
Create Date: 2024-12-18 10:50:22.592910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c02e4655cd5'
down_revision: Union[str, None] = '2104298d3ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SalesJobDocuments')
    op.drop_table('SalesJobDocumentCategory')
    op.drop_table('SalesJobDocumentCategoryDocuments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SalesJobDocuments',
    sa.Column('salesJobDocumentsID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('salesJobDocumentCategoryID', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['salesJobDocumentCategoryID'], ['SalesJobDocumentCategory.salesJobDocumentCategoryID'], name='SalesJobDocuments_salesJobDocumentCategoryID_fkey'),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], name='SalesJobDocuments_salesJobID_fkey'),
    sa.PrimaryKeyConstraint('salesJobDocumentsID', name='SalesJobDocuments_pkey')
    )
    op.create_table('SalesJobDocumentCategory',
    sa.Column('salesJobDocumentCategoryID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('salesJobDocumentCategoryName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsID', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['salesJobDocumentCategoryDocumentsID'], ['SalesJobDocumentCategoryDocuments.salesJobDocumentCategoryDocumentsID'], name='SalesJobDocumentCategory_salesJobDocumentCategoryDocuments_fkey'),
    sa.PrimaryKeyConstraint('salesJobDocumentCategoryID', name='SalesJobDocumentCategory_pkey')
    )
    op.create_table('SalesJobDocumentCategoryDocuments',
    sa.Column('salesJobDocumentCategoryDocumentsID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsRequiredName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsRequiredURL', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsAdditionalURL', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsUploadedDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsNote', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('salesJobDocumentCategoryDocumentsUploadedByID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['salesJobDocumentCategoryDocumentsUploadedByID'], ['EmployeeMaster.employeeID'], name='SalesJobDocumentCategoryDocum_salesJobDocumentCategoryDocu_fkey'),
    sa.PrimaryKeyConstraint('salesJobDocumentCategoryDocumentsID', name='SalesJobDocumentCategoryDocuments_pkey')
    )
    # ### end Alembic commands ###
