"""salesJobPreviewedByID added in salesjob

Revision ID: 119ad33119da
Revises: acbdacfee44a
Create Date: 2024-12-18 21:44:19.094857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119ad33119da'
down_revision: Union[str, None] = 'acbdacfee44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SalesJob', sa.Column('salesJobPreviewedByID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJob', 'EmployeeMaster', ['salesJobPreviewedByID'], ['employeeID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SalesJob', type_='foreignkey')
    op.drop_column('SalesJob', 'salesJobPreviewedByID')
    # ### end Alembic commands ###
