"""ConstantsDeliveryWarehouse table created

Revision ID: 2104298d3ac7
Revises: 351556379a34
Create Date: 2024-12-17 15:11:56.736028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2104298d3ac7'
down_revision: Union[str, None] = '351556379a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConstantsDeliveryWarehouse',
    sa.Column('constantsDeliveryWarehouseID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsDeliveryWarehouseName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsDeliveryWarehouseID')
    )
    op.create_table('ConstantsMaterialsVendor',
    sa.Column('constantsMaterialsVendorID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsMaterialsVendorName', sa.String(length=255), nullable=False),
    sa.Column('constantsMaterialsVendorActive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsMaterialsVendorID')
    )
    op.create_table('SalesJobMaterials',
    sa.Column('salesJobMaterialsID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('salesJobMaterialsItemsName', sa.String(length=225), nullable=False),
    sa.Column('salesJobMaterialsItemsQuantity', sa.Integer(), nullable=False),
    sa.Column('salesJobMaterialsAllMaterialsIsReceived', sa.Boolean(), nullable=False),
    sa.Column('salesJobMaterialsVendorID', sa.Integer(), nullable=True),
    sa.Column('salesJobMaterialsOrderNumber', sa.Integer(), nullable=False),
    sa.Column('salesJobMaterialsDateOrdered', sa.DateTime(), nullable=False),
    sa.Column('salesJobMaterialsEstimatedShipDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobMaterialsShippedDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobMaterialsShippingCarrier', sa.String(length=225), nullable=False),
    sa.Column('salesJobMaterialsTrackingNumber', sa.String(length=225), nullable=False),
    sa.Column('salesJobMaterialsDeliveryWarehouseID', sa.Integer(), nullable=True),
    sa.Column('salesJobMaterialsOrderedNotes', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.ForeignKeyConstraint(['salesJobMaterialsDeliveryWarehouseID'], ['ConstantsDeliveryWarehouse.constantsDeliveryWarehouseID'], ),
    sa.ForeignKeyConstraint(['salesJobMaterialsVendorID'], ['ConstantsMaterialsVendor.constantsMaterialsVendorID'], ),
    sa.PrimaryKeyConstraint('salesJobMaterialsID')
    )
    op.drop_table('SalesJobMaterialsOrdered')
    op.drop_table('MaterialsVendor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SalesJobMaterialsOrdered',
    sa.Column('salesJobMaterialsOrderedID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('salesMaterialsOrderedOrderNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsOrderedItemName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsOrderedVendorID', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('salesJobMaterialsOrderNumber', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsDateOrdered', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsEstimatedShipDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsShippedDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsShippingCarrier', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsTrackingNumber', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsDeliveryLocation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsReceivedDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsIsReceived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('salesJobMaterialsOrderedNotes', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], name='SalesJobMaterialsOrdered_salesJobID_fkey'),
    sa.ForeignKeyConstraint(['salesJobMaterialsOrderedVendorID'], ['MaterialsVendor.materialsVendorID'], name='SalesJobMaterialsOrdered_salesJobMaterialsOrderedVendorID_fkey'),
    sa.PrimaryKeyConstraint('salesJobMaterialsOrderedID', name='SalesJobMaterialsOrdered_pkey')
    )
    op.create_table('MaterialsVendor',
    sa.Column('materialsVendorID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('materialsVendorName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('materialsVendorActive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('materialsVendorID', name='MaterialsVendor_pkey')
    )
    op.drop_table('SalesJobMaterials')
    op.drop_table('ConstantsMaterialsVendor')
    op.drop_table('ConstantsDeliveryWarehouse')
    # ### end Alembic commands ###
