"""constants tables creation and relation is updating

Revision ID: 272f16d08279
Revises: 7bb10b87c3f3
Create Date: 2024-12-03 17:04:13.375709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '272f16d08279'
down_revision: Union[str, None] = '7bb10b87c3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConstantsAppointmentDisposition',
    sa.Column('constantsAppointmentDispositionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsAppointmentDisposition', sa.String(length=255), nullable=False),
    sa.Column('constantsAppointmentDispositionDescription', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsAppointmentDispositionID')
    )
    op.create_table('ConstantsEmployeePayType',
    sa.Column('constantsEmployeePayTypeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsEmployeePayTypeName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEmployeePayTypeID')
    )
    op.create_table('ConstantsEmployeeType',
    sa.Column('constantsEmployeeTypeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsEmployeeTypeName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEmployeeTypeID')
    )
    op.create_table('ConstantsEntityCallResult',
    sa.Column('constantsEntityCallResultID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsEntityCallResultName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityCallResultID')
    )
    op.create_table('ConstantsEntityCallType',
    sa.Column('constantsEntityCallTypeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsEntityCallTypeName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityCallTypeID')
    )
    op.create_table('ConstantsEntityEmploymentStatus',
    sa.Column('constantsEntityEmploymentStatusID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsEntityEmploymentStatusName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityEmploymentStatusID')
    )
    op.create_table('ConstantsEntityMaritalStatus',
    sa.Column('constantsEntityMaritalStatusID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsEntityMaritalStatusName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityMaritalStatusID')
    )
    op.create_table('ConstantsEntityPropertyStructure',
    sa.Column('constantsEntityPropertyStructureID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsEntityPropertyStructureName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityPropertyStructureID')
    )
    op.create_table('ConstantsEntitySource',
    sa.Column('constantsEntitySourceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsEntitySourceName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntitySourceID')
    )
    op.create_table('ConstantsMarketType',
    sa.Column('constantsMarketID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsMarketName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsMarketID')
    )
    op.create_table('ConstantsPhoneType',
    sa.Column('constantsPhoneTypeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsPhoneTypeName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsPhoneTypeID')
    )
    op.create_table('ConstantsProductType',
    sa.Column('constantsProductID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsProductName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsProductID')
    )
    op.create_table('ConstantsPropertyLookUp',
    sa.Column('constantsPropertyLookUpID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsPropertyLookUpName', sa.String(length=255), nullable=False),
    sa.Column('constantsPropertyLookUpLink', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsPropertyLookUpID')
    )
    op.create_table('ConstantsSalesJobDispositon',
    sa.Column('constantsSalesJobDispositonID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsSalesJobDispositionName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsSalesJobDispositonID')
    )
    op.create_table('ConstantsEntitySubSource',
    sa.Column('constantsEntitySubSourceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsEntitySubSourceName', sa.String(length=255), nullable=False),
    sa.Column('constantsEntitySourceID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['constantsEntitySourceID'], ['ConstantsEntitySource.constantsEntitySourceID'], ),
    sa.PrimaryKeyConstraint('constantsEntitySubSourceID')
    )
    op.create_table('EntityAppointmentSelectedProduct',
    sa.Column('entityAppointmentSelectedProductID', sa.UUID(), nullable=False),
    sa.Column('entityAppointmentsID', sa.UUID(), nullable=True),
    sa.Column('constantsProductID', sa.Integer(), nullable=True),
    sa.Column('entityAppointmentSelectedProductQuanity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['constantsProductID'], ['ConstantsProductType.constantsProductID'], ),
    sa.ForeignKeyConstraint(['entityAppointmentsID'], ['EntityAppointments.entityAppointmentsID'], ),
    sa.PrimaryKeyConstraint('entityAppointmentSelectedProductID')
    )
    op.add_column('EmployeeMaster', sa.Column('employeeTypeID', sa.Integer(), nullable=True))
    op.add_column('EmployeeMaster', sa.Column('employeePayTypeID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'EmployeeMaster', 'ConstantsEmployeePayType', ['employeePayTypeID'], ['constantsEmployeePayTypeID'])
    op.create_foreign_key(None, 'EmployeeMaster', 'ConstantsEmployeeType', ['employeeTypeID'], ['constantsEmployeeTypeID'])
    op.add_column('Entity', sa.Column('entityInboundRecordLockedByID', sa.UUID(), nullable=True))
    op.alter_column('Entity', 'entityPrefix',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Entity', 'entityInitialDataReceivedNotes',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('Entity', 'entityInboundRecordIsLocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('Entity', 'entityNotes',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.create_foreign_key(None, 'Entity', 'EmployeeMaster', ['entityInboundRecordLockedByID'], ['employeeID'])
    op.drop_column('Entity', 'entityInboundRecordLockedBy')
    op.add_column('EntityAppointments', sa.Column('constantsAppointmentDispositionID', sa.Integer(), nullable=True))
    op.drop_constraint('EntityAppointments_entitySelectedProductID_fkey', 'EntityAppointments', type_='foreignkey')
    op.create_foreign_key(None, 'EntityAppointments', 'ConstantsAppointmentDisposition', ['constantsAppointmentDispositionID'], ['constantsAppointmentDispositionID'])
    op.drop_column('EntityAppointments', 'entityAppointmentsCurrentEntityTypeID')
    op.drop_column('EntityAppointments', 'entityAppointmentsLeadSubSource')
    op.drop_column('EntityAppointments', 'entityAppointmentsLeadSource')
    op.drop_column('EntityAppointments', 'entitySelectedProductID')
    op.add_column('EntityPhone', sa.Column('constantsPhoneTypeID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'EntityPhone', 'ConstantsPhoneType', ['constantsPhoneTypeID'], ['constantsPhoneTypeID'])
    op.add_column('EntityProperty', sa.Column('constantsMarketID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'EntityProperty', 'ConstantsMarketType', ['constantsMarketID'], ['constantsMarketID'])
    op.drop_column('EntityProperty', 'entityPropertyMarket')
    op.add_column('SalesJob', sa.Column('salesJobDispositionID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJob', 'ConstantsSalesJobDispositon', ['salesJobDispositionID'], ['constantsSalesJobDispositonID'])
    op.add_column('SalesJobDocuments', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobDocuments', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobPermits', sa.Column('salesJobPermitsS3URL', sa.String(length=255), nullable=False))
    op.add_column('SubContractor', sa.Column('subContractorMarketID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SubContractor', 'ConstantsMarketType', ['subContractorMarketID'], ['constantsMarketID'])
    op.drop_table('EntitySelectedProduct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SubContractor', type_='foreignkey')
    op.drop_column('SubContractor', 'subContractorMarketID')
    op.drop_column('SalesJobPermits', 'salesJobPermitsS3URL')
    op.drop_constraint(None, 'SalesJobDocuments', type_='foreignkey')
    op.drop_column('SalesJobDocuments', 'salesJobID')
    op.drop_constraint(None, 'SalesJob', type_='foreignkey')
    op.drop_column('SalesJob', 'salesJobDispositionID')
    op.add_column('EntityProperty', sa.Column('entityPropertyMarket', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EntityProperty', type_='foreignkey')
    op.drop_column('EntityProperty', 'constantsMarketID')
    op.drop_constraint(None, 'EntityPhone', type_='foreignkey')
    op.drop_column('EntityPhone', 'constantsPhoneTypeID')
    op.add_column('EntityAppointments', sa.Column('entitySelectedProductID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsLeadSource', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsLeadSubSource', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsCurrentEntityTypeID', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EntityAppointments', type_='foreignkey')
    op.create_foreign_key('EntityAppointments_entitySelectedProductID_fkey', 'EntityAppointments', 'EntitySelectedProduct', ['entitySelectedProductID'], ['entitySelectedProductID'])
    op.drop_column('EntityAppointments', 'constantsAppointmentDispositionID')
    op.add_column('Entity', sa.Column('entityInboundRecordLockedBy', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Entity', type_='foreignkey')
    op.alter_column('Entity', 'entityNotes',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('Entity', 'entityInboundRecordIsLocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('Entity', 'entityInitialDataReceivedNotes',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('Entity', 'entityPrefix',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('Entity', 'entityInboundRecordLockedByID')
    op.drop_constraint(None, 'EmployeeMaster', type_='foreignkey')
    op.drop_constraint(None, 'EmployeeMaster', type_='foreignkey')
    op.drop_column('EmployeeMaster', 'employeePayTypeID')
    op.drop_column('EmployeeMaster', 'employeeTypeID')
    op.create_table('EntitySelectedProduct',
    sa.Column('entitySelectedProductID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entitySelectedProductName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('entitySelectedProductQuanity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('entitySelectedProductID', name='EntitySelectedProduct_pkey')
    )
    op.drop_table('EntityAppointmentSelectedProduct')
    op.drop_table('ConstantsEntitySubSource')
    op.drop_table('ConstantsSalesJobDispositon')
    op.drop_table('ConstantsPropertyLookUp')
    op.drop_table('ConstantsProductType')
    op.drop_table('ConstantsPhoneType')
    op.drop_table('ConstantsMarketType')
    op.drop_table('ConstantsEntitySource')
    op.drop_table('ConstantsEntityPropertyStructure')
    op.drop_table('ConstantsEntityMaritalStatus')
    op.drop_table('ConstantsEntityEmploymentStatus')
    op.drop_table('ConstantsEntityCallType')
    op.drop_table('ConstantsEntityCallResult')
    op.drop_table('ConstantsEmployeeType')
    op.drop_table('ConstantsEmployeePayType')
    op.drop_table('ConstantsAppointmentDisposition')
    # ### end Alembic commands ###
