"""phone table created

Revision ID: 27542fb80df5
Revises: 3eb49b3e2426
Create Date: 2024-11-29 14:25:44.579728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27542fb80df5'
down_revision: Union[str, None] = '3eb49b3e2426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EntityPhone',
    sa.Column('phoneID', sa.UUID(), nullable=False),
    sa.Column('entityID', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('phoneType', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityID'], ['Entity.entityID'], ),
    sa.PrimaryKeyConstraint('phoneID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EntityPhone')
    # ### end Alembic commands ###
