"""EntityDispute table is created

Revision ID: 3478b054e58b
Revises: 272f16d08279
Create Date: 2024-12-04 00:30:38.263856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3478b054e58b'
down_revision: Union[str, None] = '272f16d08279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EntityDispute',
    sa.Column('entityDisputeID', sa.UUID(), nullable=False),
    sa.Column('entityID', sa.UUID(), nullable=True),
    sa.Column('entityDisputeSource', sa.String(length=255), nullable=False),
    sa.Column('entityDisputeSubSource', sa.String(length=255), nullable=False),
    sa.Column('entityDisputeProduct', sa.String(length=255), nullable=False),
    sa.Column('entityDisputeInitialDataReceivedDate', sa.DateTime(), nullable=False),
    sa.Column('entityDisputeIsProcessed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entityID'], ['Entity.entityID'], ),
    sa.PrimaryKeyConstraint('entityDisputeID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EntityDispute')
    # ### end Alembic commands ###
