"""commissionReport and SalesJobAddendum updated

Revision ID: 351556379a34
Revises: fda3e6bb359a
Create Date: 2024-12-17 11:26:33.855665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351556379a34'
down_revision: Union[str, None] = 'fda3e6bb359a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CommissionReport', sa.Column('commissionReportIsRedFlagged', sa.Boolean(), nullable=False))
    op.alter_column('CommissionReport', 'commissionReportNotes',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('CommissionReport', 'commissionReportS3URL',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumPositiveCommissionAmount', sa.String(length=255), nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumIsRejected', sa.Boolean(), nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumS3URL', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SalesJobAddendum', 'salesJobAddendumS3URL')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumIsRejected')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumPositiveCommissionAmount')
    op.alter_column('CommissionReport', 'commissionReportS3URL',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('CommissionReport', 'commissionReportNotes',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('CommissionReport', 'commissionReportIsRedFlagged')
    # ### end Alembic commands ###
