"""added enum in SubContractor and SubContractorEmployee

Revision ID: 3eb49b3e2426
Revises: d7cc55fd91e4
Create Date: 2024-11-28 11:44:24.092959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3eb49b3e2426'
down_revision: Union[str, None] = 'd7cc55fd91e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EntityCallback', 'entityCallbackIsComplete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('SubContractor', sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='statusenum'), nullable=False))
    op.add_column('SubContractorEmployee', sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='statusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SubContractorEmployee', 'status')
    op.drop_column('SubContractor', 'status')
    op.alter_column('EntityCallback', 'entityCallbackIsComplete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
