"""EntityDispute and Appointmnet table updated

Revision ID: 534e13a3f3d6
Revises: 3478b054e58b
Create Date: 2024-12-06 10:15:43.745786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534e13a3f3d6'
down_revision: Union[str, None] = '3478b054e58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsMarketID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'EntityAppointments', 'ConstantsMarketType', ['entityAppointmentsMarketID'], ['constantsMarketID'])
    op.drop_column('EntityAppointments', 'entityAppointmentsMarket')
    op.add_column('EntityDispute', sa.Column('entityDisputeFirstName', sa.String(length=255), nullable=False, server_default=""))
    op.add_column('EntityDispute', sa.Column('entityDisputeLastName', sa.String(length=255), nullable=False, server_default=""))
    op.add_column('EntityDispute', sa.Column('parentEntityID', sa.UUID(), nullable=True))
    op.add_column('EntityDispute', sa.Column('parentEntityInboundRecordNumber', sa.Integer(), nullable=False, server_default=""))
    op.add_column('EntityDispute', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('EntityDispute_entityID_fkey', 'EntityDispute', type_='foreignkey')
    op.create_foreign_key(None, 'EntityDispute', 'Entity', ['parentEntityID'], ['entityID'])
    op.drop_column('EntityDispute', 'entityID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EntityDispute', sa.Column('entityID', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'EntityDispute', type_='foreignkey')
    op.create_foreign_key('EntityDispute_entityID_fkey', 'EntityDispute', 'Entity', ['entityID'], ['entityID'])
    op.drop_column('EntityDispute', 'created_at')
    op.drop_column('EntityDispute', 'parentEntityInboundRecordNumber')
    op.drop_column('EntityDispute', 'parentEntityID')
    op.drop_column('EntityDispute', 'entityDisputeLastName')
    op.drop_column('EntityDispute', 'entityDisputeFirstName')
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsMarket', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EntityAppointments', type_='foreignkey')
    op.drop_column('EntityAppointments', 'entityAppointmentsMarketID')
    # ### end Alembic commands ###
