"""models created

Revision ID: 5e8024e0bd1d
Revises: 
Create Date: 2024-11-16 13:29:43.844857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8024e0bd1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SamMultiLambdaAppBaseTable',
    sa.Column('samMultiLambdaAppBaseTableID', sa.UUID(), nullable=False),
    sa.Column('baseSalesJobNumber', sa.Integer(), nullable=False),
    sa.Column('baseAppointmentNumber', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('samMultiLambdaAppBaseTableID')
    )
    op.create_table('ConstantsJobStatus',
    sa.Column('constantsJobStatusID', sa.UUID(), nullable=False),
    sa.Column('constantsJobStatusName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsJobStatusID')
    )
    op.create_table('ConstantsMarketType',
    sa.Column('constantsMarketID', sa.UUID(), nullable=False),
    sa.Column('constantsMarketName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsMarketID')
    )
    op.create_table('ConstantsProductType',
    sa.Column('constantsProductID', sa.UUID(), nullable=False),
    sa.Column('constantsProductName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsProductID')
    )
    op.create_table('ConstantsPropertyAppointmentState',
    sa.Column('constantsPropertyAppointmentStateID', sa.UUID(), nullable=False),
    sa.Column('constantsPropertyState', sa.String(length=255), nullable=False),
    sa.Column('constantsAppointmentState', sa.String(length=255), nullable=False),
    sa.Column('constantsAppointmentStateDescription', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsPropertyAppointmentStateID')
    )
    op.create_table('EmployeeMaster',
    sa.Column('employeeID', sa.UUID(), nullable=False),
    sa.Column('employeeBadgeID', sa.Integer(), nullable=False),
    sa.Column('employeeFirstName', sa.String(length=255), nullable=False),
    sa.Column('employeeLastName', sa.String(length=255), nullable=False),
    sa.Column('employeeHireDate', sa.DateTime(), nullable=False),
    sa.Column('employeeTerminationDate', sa.DateTime(), nullable=False),
    sa.Column('employeeActive', sa.Boolean(), nullable=False),
    sa.Column('employeeUserName', sa.String(length=255), nullable=False),
    sa.Column('employeePassword', sa.String(length=255), nullable=False),
    sa.Column('employeeType', sa.String(length=255), nullable=False),
    sa.Column('employeePayType', sa.String(length=255), nullable=False),
    sa.Column('employeeStartFullTimeSalary', sa.String(length=255), nullable=False),
    sa.Column('employeeChangeInFullTimeSalary', sa.String(length=255), nullable=False),
    sa.Column('employeeChangeInFullTimeSalaryEffectiveDate', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employeeID')
    )
    op.create_table('EntitySelectedProduct',
    sa.Column('entitySelectedProductID', sa.UUID(), nullable=False),
    sa.Column('entitySelectedProductName', sa.String(length=255), nullable=False),
    sa.Column('entitySelectedProductQuanity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('entitySelectedProductID')
    )
    op.create_table('MasterPayrollPeriod',
    sa.Column('masterPayrollPeriodID', sa.UUID(), nullable=False),
    sa.Column('masterPayrollPeriodYear', sa.String(length=255), nullable=False),
    sa.Column('masterPayrollPeriodPayDate', sa.DateTime(), nullable=False),
    sa.Column('masterPayrollPeriodPayStartDate', sa.DateTime(), nullable=False),
    sa.Column('masterPayrollPeriodPayEndDate', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('masterPayrollPeriodID')
    )
    op.create_table('MaterialsVendor',
    sa.Column('materialsVendorID', sa.UUID(), nullable=False),
    sa.Column('materialsVendorName', sa.String(length=255), nullable=False),
    sa.Column('materialsVendorActive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('materialsVendorID')
    )
    op.create_table('SubContractor',
    sa.Column('subContractorID', sa.UUID(), nullable=False),
    sa.Column('subContractorCompanyName', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyAddressLine1', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyAddressLine2', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyCity', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyState', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyZipCode', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyPhone', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyEmail', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyLicenseNumber', sa.String(length=255), nullable=False),
    sa.Column('subContractorOwnerFirsttName', sa.String(length=255), nullable=False),
    sa.Column('subContractorOwnerLastName', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyOwnerPhone', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyOwnerEmail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subContractorID')
    )
    op.create_table('Entity',
    sa.Column('entityID', sa.UUID(), nullable=False),
    sa.Column('entityInboundRecordNumber', sa.String(length=255), nullable=False),
    sa.Column('entityInboundRecordStatus', sa.String(length=255), nullable=False),
    sa.Column('entityCustomerRecordNumber', sa.String(length=255), nullable=True),
    sa.Column('entityIsInboundDuplicateRecord', sa.Boolean(), nullable=False),
    sa.Column('entityIsInboundRecordMerged', sa.Boolean(), nullable=False),
    sa.Column('entityIsInboundRecordDeleted', sa.Boolean(), nullable=False),
    sa.Column('entityPrefix', sa.String(length=255), nullable=False),
    sa.Column('entityFirstName', sa.String(length=255), nullable=False),
    sa.Column('entityLastName', sa.String(length=255), nullable=False),
    sa.Column('constantsProductID', sa.UUID(), nullable=True),
    sa.Column('entityPermanentAddressLine1', sa.String(length=255), nullable=False),
    sa.Column('entityPermanentAddressLine2', sa.String(length=255), nullable=False),
    sa.Column('entityPermanentCity', sa.String(length=255), nullable=False),
    sa.Column('entityPermanentState', sa.String(length=255), nullable=False),
    sa.Column('entityPermanentZipcode', sa.String(length=255), nullable=False),
    sa.Column('entityPhone', sa.String(length=255), nullable=False),
    sa.Column('entityPhoneType', sa.String(length=255), nullable=False),
    sa.Column('entityrDoNotText', sa.Boolean(), nullable=False),
    sa.Column('entityDoNotEmail', sa.Boolean(), nullable=False),
    sa.Column('entityDoNotCall', sa.Boolean(), nullable=False),
    sa.Column('entityDNCWaiver', sa.Boolean(), nullable=False),
    sa.Column('entityEmail', sa.String(length=255), nullable=False),
    sa.Column('entityInitialDataReceivedDate', sa.DateTime(), nullable=False),
    sa.Column('entityInitialDataReceivedSource', sa.String(length=255), nullable=False),
    sa.Column('entityInitialDataReceivedSubSource', sa.String(length=255), nullable=False),
    sa.Column('entityInitialDataReceivedNotes', sa.String(length=255), nullable=False),
    sa.Column('entityInitialDataReceivedCheckoutDate', sa.DateTime(), nullable=False),
    sa.Column('entityInitialDataReceivedCheckedOutByID', sa.String(length=255), nullable=False),
    sa.Column('constantsMarketID', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['constantsMarketID'], ['ConstantsMarketType.constantsMarketID'], ),
    sa.ForeignKeyConstraint(['constantsProductID'], ['ConstantsProductType.constantsProductID'], ),
    sa.PrimaryKeyConstraint('entityID')
    )
    op.create_table('SalesJobDocumentCategoryDocuments',
    sa.Column('salesJobDocumentCategoryDocumentsID', sa.UUID(), nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsRequiredName', sa.String(length=255), nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsRequiredURL', sa.String(length=255), nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsAdditionalURL', sa.String(length=255), nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsUploadedByID', sa.UUID(), nullable=True),
    sa.Column('salesJobDocumentCategoryDocumentsUploadedDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsNote', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobDocumentCategoryDocumentsUploadedByID'], ['EmployeeMaster.employeeID'], ),
    sa.PrimaryKeyConstraint('salesJobDocumentCategoryDocumentsID')
    )
    op.create_table('SubContractorEmployee',
    sa.Column('subContractorEmployeeID', sa.UUID(), nullable=False),
    sa.Column('subContractorID', sa.UUID(), nullable=True),
    sa.Column('subContractorEmployeeFirstName', sa.String(length=255), nullable=False),
    sa.Column('subContractorEmployeeLastName', sa.String(length=255), nullable=False),
    sa.Column('subContractorEmployeePhone', sa.String(length=255), nullable=False),
    sa.Column('subContractorEmployeeEmail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subContractorID'], ['SubContractor.subContractorID'], ),
    sa.PrimaryKeyConstraint('subContractorEmployeeID')
    )
    op.create_table('EntityCall',
    sa.Column('entityCallID', sa.UUID(), nullable=False),
    sa.Column('entityID', sa.UUID(), nullable=True),
    sa.Column('entityCallCallResult', sa.String(length=255), nullable=False),
    sa.Column('entityCallPhone', sa.String(length=255), nullable=False),
    sa.Column('entityCallDate', sa.DateTime(), nullable=False),
    sa.Column('entityCallCode', sa.String(length=255), nullable=False),
    sa.Column('entityCallCaller', sa.String(length=255), nullable=False),
    sa.Column('entityCallCallType', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityID'], ['Entity.entityID'], ),
    sa.PrimaryKeyConstraint('entityCallID')
    )
    op.create_table('EntityCallCenterNotes',
    sa.Column('entityCallCenterNotesID', sa.UUID(), nullable=False),
    sa.Column('entityID', sa.UUID(), nullable=True),
    sa.Column('entityCallCenterNotesNotes', sa.String(length=255), nullable=False),
    sa.Column('entityCallCenterNotesDate', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityID'], ['Entity.entityID'], ),
    sa.PrimaryKeyConstraint('entityCallCenterNotesID')
    )
    op.create_table('EntityProperty',
    sa.Column('entityPropertyID', sa.UUID(), nullable=False),
    sa.Column('entityID', sa.UUID(), nullable=True),
    sa.Column('entityPropertyAddressLine1', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyAddressLine2', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyCity', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyState', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyZip', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyDirections', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyMarket', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyStructure', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityID'], ['Entity.entityID'], ),
    sa.PrimaryKeyConstraint('entityPropertyID')
    )
    op.create_table('EntitySecondaryContactDetails',
    sa.Column('customerSecondaryContactDetailsID', sa.UUID(), nullable=False),
    sa.Column('entityID', sa.UUID(), nullable=True),
    sa.Column('entitySecondaryContactFirstName', sa.String(length=255), nullable=False),
    sa.Column('entitySecondaryContactLastName', sa.String(length=255), nullable=False),
    sa.Column('entitySecondaryContactRelationshipType', sa.String(length=255), nullable=False),
    sa.Column('entitySecondaryContactDetailsPhone', sa.String(length=255), nullable=False),
    sa.Column('entitySecondaryContactDetailsPhoneType', sa.String(length=255), nullable=False),
    sa.Column('entitySecondaryContactDetailsEmail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityID'], ['Entity.entityID'], ),
    sa.PrimaryKeyConstraint('customerSecondaryContactDetailsID')
    )
    op.create_table('SalesJobDocumentCategory',
    sa.Column('salesJobDocumentCategoryID', sa.UUID(), nullable=False),
    sa.Column('salesJobDocumentCategoryName', sa.String(length=255), nullable=False),
    sa.Column('salesJobDocumentCategoryDocumentsID', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobDocumentCategoryDocumentsID'], ['SalesJobDocumentCategoryDocuments.salesJobDocumentCategoryDocumentsID'], ),
    sa.PrimaryKeyConstraint('salesJobDocumentCategoryID')
    )
    op.create_table('EntityAppointments',
    sa.Column('entityAppointmentsID', sa.UUID(), nullable=False),
    sa.Column('entityAppointmentNumber', sa.Integer(), nullable=False),
    sa.Column('entityPropertyID', sa.UUID(), nullable=True),
    sa.Column('constantsPropertyAppointmentStateID', sa.UUID(), nullable=True),
    sa.Column('entityAppointmentsLeadEntryDate', sa.DateTime(), nullable=False),
    sa.Column('entityAppointmentsLeadTime', sa.DateTime(), nullable=False),
    sa.Column('entitySelectedProductID', sa.UUID(), nullable=True),
    sa.Column('entityAppointmentsSalesRep1', sa.UUID(), nullable=True),
    sa.Column('entityAppointmentsSalesRep2', sa.UUID(), nullable=True),
    sa.Column('entityAppointmentsMarket', sa.String(length=255), nullable=False),
    sa.Column('entityAppointmentsLeadSource', sa.String(length=255), nullable=False),
    sa.Column('entityAppointmentsLeadSubSource', sa.String(length=255), nullable=False),
    sa.Column('entityAppointmentsHDBadgeID', sa.String(length=255), nullable=False),
    sa.Column('entityAppointmentsBCICallID', sa.String(length=255), nullable=False),
    sa.Column('entityAppointmentsAppointmentDate', sa.DateTime(), nullable=False),
    sa.Column('entityAppointmentsAppointmentTime', sa.DateTime(), nullable=False),
    sa.Column('entityAppointmentsCurrentEntityTypeID', sa.String(length=255), nullable=False),
    sa.Column('entityAppointmentsLeadSetterID', sa.UUID(), nullable=True),
    sa.Column('entityAppointmentsSOW', sa.String(length=255), nullable=False),
    sa.Column('entityAppointmentsGoodWith90Minutes', sa.Boolean(), nullable=False),
    sa.Column('entityAppointmentsHOA', sa.Boolean(), nullable=False),
    sa.Column('entityAppointmentsGoodWithPermits', sa.Boolean(), nullable=False),
    sa.Column('entityAppointmentsRentalProperty', sa.Boolean(), nullable=False),
    sa.Column('entityAppointmentsDecisionMakers', sa.String(length=255), nullable=False),
    sa.Column('entityAppointmentsNotes', sa.String(length=255), nullable=False),
    sa.Column('entityAppointmentsIssued', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['constantsPropertyAppointmentStateID'], ['ConstantsPropertyAppointmentState.constantsPropertyAppointmentStateID'], ),
    sa.ForeignKeyConstraint(['entityAppointmentsLeadSetterID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['entityAppointmentsSalesRep1'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['entityAppointmentsSalesRep2'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['entityPropertyID'], ['EntityProperty.entityPropertyID'], ),
    sa.ForeignKeyConstraint(['entitySelectedProductID'], ['EntitySelectedProduct.entitySelectedProductID'], ),
    sa.PrimaryKeyConstraint('entityAppointmentsID')
    )
    op.create_table('EntityCallback',
    sa.Column('entityCallbackID', sa.UUID(), nullable=False),
    sa.Column('entityCallID', sa.UUID(), nullable=True),
    sa.Column('entityCallbackDate', sa.DateTime(), nullable=False),
    sa.Column('entityCallbackTime', sa.DateTime(), nullable=False),
    sa.Column('entityCallbackAssignedTo', sa.UUID(), nullable=True),
    sa.Column('entityCallbackPhone', sa.String(length=255), nullable=False),
    sa.Column('entityCallbackComplete', sa.Boolean(), nullable=False),
    sa.Column('entityCallbackNotes', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityCallID'], ['EntityCall.entityCallID'], ),
    sa.ForeignKeyConstraint(['entityCallbackAssignedTo'], ['EmployeeMaster.employeeID'], ),
    sa.PrimaryKeyConstraint('entityCallbackID')
    )
    op.create_table('EntityPropertyContact',
    sa.Column('entityPropertyContactID', sa.UUID(), nullable=False),
    sa.Column('entityPropertyID', sa.UUID(), nullable=True),
    sa.Column('entityPropertyContactPrefix', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyContactFirstName', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyContactLastName', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyContactRelationType', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyContactPhone', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyContactPhoneType', sa.String(length=255), nullable=False),
    sa.Column('entityPropertyContactEmail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityPropertyID'], ['EntityProperty.entityPropertyID'], ),
    sa.PrimaryKeyConstraint('entityPropertyContactID')
    )
    op.create_table('SalesJob',
    sa.Column('salesJobID', sa.UUID(), nullable=False),
    sa.Column('entityPropertyID', sa.UUID(), nullable=True),
    sa.Column('salesJobNumber', sa.String(length=255), nullable=False),
    sa.Column('salesJobName', sa.String(length=255), nullable=False),
    sa.Column('salesJobContractDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobStartDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobCompleteDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobGrossAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobStatusID', sa.UUID(), nullable=True),
    sa.Column('salesJobLeadRequirement', sa.Boolean(), nullable=False),
    sa.Column('salesJobSubContractorID', sa.UUID(), nullable=True),
    sa.Column('salesJobMeasuredByID', sa.UUID(), nullable=True),
    sa.Column('salesJobLastPriceOfferedAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobSalesPersonID', sa.UUID(), nullable=True),
    sa.Column('salesJobProjectManagerID', sa.UUID(), nullable=True),
    sa.Column('salesJobFinanceOption', sa.String(length=255), nullable=False),
    sa.Column('salesJobNotes', sa.String(length=255), nullable=False),
    sa.Column('salesJobQualityControlled', sa.Boolean(), nullable=False),
    sa.Column('salesJobVoucherSentDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobArchitectureApplicationNeeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityPropertyID'], ['EntityProperty.entityPropertyID'], ),
    sa.ForeignKeyConstraint(['salesJobMeasuredByID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobProjectManagerID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobSalesPersonID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobStatusID'], ['ConstantsJobStatus.constantsJobStatusID'], ),
    sa.ForeignKeyConstraint(['salesJobSubContractorID'], ['SubContractor.subContractorID'], ),
    sa.PrimaryKeyConstraint('salesJobID')
    )
    op.create_table('SalesJobDocuments',
    sa.Column('salesJobDocumentsID', sa.UUID(), nullable=False),
    sa.Column('salesJobDocumentCategoryID', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobDocumentCategoryID'], ['SalesJobDocumentCategory.salesJobDocumentCategoryID'], ),
    sa.PrimaryKeyConstraint('salesJobDocumentsID')
    )
    op.create_table('CommissionReport',
    sa.Column('commissionReportID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('commissionReportDate', sa.DateTime(), nullable=False),
    sa.Column('commissionReportDesignConsultanID', sa.UUID(), nullable=True),
    sa.Column('commissionReportDesignConsultantName', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerName', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerEmail1', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerEmail2', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerEmail3', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerAddressLine1', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerAddressLine2', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerCity', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerState', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerZip', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerPhone1', sa.String(length=225), nullable=False),
    sa.Column('commissionReportCustomerPhone2', sa.String(length=225), nullable=False),
    sa.Column('commissionReportRevisedContractPrice', sa.String(length=225), nullable=False),
    sa.Column('commissionReportTotalCommissionOnNonCommercialItems', sa.String(length=225), nullable=False),
    sa.Column('commissionReportTotalCommissionPrice', sa.String(length=225), nullable=False),
    sa.Column('commissionReportExpectedPrepayCommissionPrice', sa.String(length=225), nullable=False),
    sa.Column('commissionReportExpectedPrepayCommissionPriceIsProcessed', sa.Boolean(), nullable=False),
    sa.Column('commissionReportExpectedFinalCommissionPrice', sa.String(length=225), nullable=False),
    sa.Column('commissionReportExpectedFinalCommissionPriceIsProcessed', sa.Boolean(), nullable=False),
    sa.Column('commissionReportNotes', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commissionReportDesignConsultanID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.PrimaryKeyConstraint('commissionReportID')
    )
    op.create_table('ContractLineItem',
    sa.Column('contractLineItemID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('contractLineItemCategoryID', sa.String(length=255), nullable=False),
    sa.Column('contractLineItemCategoryName', sa.String(length=255), nullable=False),
    sa.Column('contractLineItemQuantiy', sa.String(length=255), nullable=False),
    sa.Column('contractLineItemUnit', sa.String(length=255), nullable=False),
    sa.Column('contractLineItemMeasure', sa.String(length=255), nullable=False),
    sa.Column('contractLineItemSelectedItem', sa.String(length=255), nullable=False),
    sa.Column('contractLineItemPriceAmount', sa.String(length=255), nullable=False),
    sa.Column('contractLineItemTotalAmount', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.PrimaryKeyConstraint('contractLineItemID')
    )
    op.create_table('EmployeePayrollBonus',
    sa.Column('employeePayrollBonusID', sa.UUID(), nullable=False),
    sa.Column('employeePayrollID', sa.String(length=255), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('employeePayrollBonusDescription', sa.String(length=255), nullable=False),
    sa.Column('employeePayrollBonusQuantity', sa.String(length=255), nullable=False),
    sa.Column('employeePayrollBonusRate', sa.String(length=255), nullable=False),
    sa.Column('employeePayrollBonusTotal', sa.String(length=255), nullable=False),
    sa.Column('employeePayrollBonusStartDate', sa.DateTime(), nullable=False),
    sa.Column('employeePayrollBonusEndDate', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.PrimaryKeyConstraint('employeePayrollBonusID')
    )
    op.create_table('SalesJobAddendum',
    sa.Column('salesJobAddendumID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('salesJobAddendumDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobAddendumDesignConsultantID', sa.UUID(), nullable=True),
    sa.Column('salesJobAddendumDesignConsultantName', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumProjectManagerID', sa.UUID(), nullable=True),
    sa.Column('salesJobAddendumCustomerName', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerEmail1', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerEmail2', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerEmail3', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerAddressLine1', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerAddressLine2', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerCity', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerState', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerZip', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerPhone1', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumCustomerPhone2', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumOriginalContractValue', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumIsIncrease', sa.Boolean(), nullable=False),
    sa.Column('salesJobAddendumInvestmentAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumPositiveCommissionAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumNegativeCommissionAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumNewAdjustedContractValue', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumSpecialInstructions', sa.String(length=255), nullable=False),
    sa.Column('salesJobAddendumIsApproved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobAddendumDesignConsultantID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobAddendumProjectManagerID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.PrimaryKeyConstraint('salesJobAddendumID')
    )
    op.create_table('SalesJobCommissions',
    sa.Column('salesJobCommissionsID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.PrimaryKeyConstraint('salesJobCommissionsID')
    )
    op.create_table('SalesJobCost',
    sa.Column('salesJobCostID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('salesJobCostItemName', sa.String(length=255), nullable=False),
    sa.Column('salesJobCostInvoiceNumber', sa.String(length=255), nullable=False),
    sa.Column('salesJobCostInvoiceDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobCostAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobCostCommissionable', sa.Boolean(), nullable=False),
    sa.Column('salesJobCostProcess', sa.Boolean(), nullable=False),
    sa.Column('salesJobCostComments', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.PrimaryKeyConstraint('salesJobCostID')
    )
    op.create_table('SalesJobFinancing',
    sa.Column('salesJobFinancingID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.PrimaryKeyConstraint('salesJobFinancingID')
    )
    op.create_table('SalesJobMaterialsOrdered',
    sa.Column('salesJobMaterialsOrderedID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('salesMaterialsOrderedOrderNumber', sa.Integer(), nullable=False),
    sa.Column('salesJobMaterialsOrderedItemName', sa.String(length=255), nullable=False),
    sa.Column('salesJobMaterialsOrderedVendorID', sa.UUID(), nullable=True),
    sa.Column('salesJobMaterialsOrderNumber', sa.String(length=255), nullable=False),
    sa.Column('salesJobMaterialsDateOrdered', sa.DateTime(), nullable=False),
    sa.Column('salesJobMaterialsEstimatedShipDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobMaterialsShippedDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobMaterialsShippingCarrier', sa.String(length=255), nullable=False),
    sa.Column('salesJobMaterialsTrackingNumber', sa.String(length=255), nullable=False),
    sa.Column('salesJobMaterialsDeliveryLocation', sa.String(length=255), nullable=False),
    sa.Column('salesJobMaterialsReceivedDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobMaterialsIsReceived', sa.Boolean(), nullable=False),
    sa.Column('salesJobMaterialsOrderedNotes', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.ForeignKeyConstraint(['salesJobMaterialsOrderedVendorID'], ['MaterialsVendor.materialsVendorID'], ),
    sa.PrimaryKeyConstraint('salesJobMaterialsOrderedID')
    )
    op.create_table('SalesJobMilestoneDate',
    sa.Column('salesJobMilestoneDateID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('salesJobMilestoneDateName', sa.String(length=255), nullable=False),
    sa.Column('salesJobMilestoneDatePlannedDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobMilestoneDateActualDate', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.PrimaryKeyConstraint('salesJobMilestoneDateID')
    )
    op.create_table('SalesJobNotes',
    sa.Column('salesJobNotesID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('salesJobNotesNotes', sa.String(length=255), nullable=False),
    sa.Column('salesJobNotesEnteredOnDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobNotesEnteredOnUserID', sa.UUID(), nullable=True),
    sa.Column('salesJobNotesNotifyToID', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.ForeignKeyConstraint(['salesJobNotesEnteredOnUserID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobNotesNotifyToID'], ['EmployeeMaster.employeeID'], ),
    sa.PrimaryKeyConstraint('salesJobNotesID')
    )
    op.create_table('SalesJobPayment',
    sa.Column('salesJobPaymentID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('salesJobPaymentInvoiceNumber', sa.String(length=255), nullable=False),
    sa.Column('salesJobPaymentDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobPaymentAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobPaymentComments', sa.String(length=255), nullable=False),
    sa.Column('salesJobPaymentEnteredByID', sa.UUID(), nullable=True),
    sa.Column('salesJobPaymentEnteredDate', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.ForeignKeyConstraint(['salesJobPaymentEnteredByID'], ['EmployeeMaster.employeeID'], ),
    sa.PrimaryKeyConstraint('salesJobPaymentID')
    )
    op.create_table('SalesJobPermits',
    sa.Column('salesJobPermitsID', sa.UUID(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('salesJobPermitsStatus', sa.Boolean(), nullable=False),
    sa.Column('salesJobPermitsType', sa.String(length=255), nullable=False),
    sa.Column('salesJobPermitsAssignedToID', sa.UUID(), nullable=True),
    sa.Column('salesJobPermitsPermitNumber', sa.String(length=255), nullable=False),
    sa.Column('salesJobPermitsPermitDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobPermitsExpirationDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobPermitsInspectionSetDate1', sa.DateTime(), nullable=False),
    sa.Column('salesJobPermitsInspectionDate1Passed', sa.Boolean(), nullable=False),
    sa.Column('salesJobPermitsInspectionSetDate2', sa.DateTime(), nullable=False),
    sa.Column('salesJobPermitsInspectionDate2Passed', sa.Boolean(), nullable=False),
    sa.Column('salesJobPermitsInspectionSetDate3', sa.DateTime(), nullable=False),
    sa.Column('salesJobPermitsInspectionDate3Passed', sa.Boolean(), nullable=False),
    sa.Column('salesJobPermitsCustomerAmountPaid', sa.String(length=255), nullable=False),
    sa.Column('salesJobPermitsCost', sa.String(length=255), nullable=False),
    sa.Column('salesJobPermitsCustomerTransactionNumber', sa.String(length=255), nullable=False),
    sa.Column('salesJobPermitsCustomerPaymentDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobPermitsEnteredByUserID', sa.String(length=255), nullable=False),
    sa.Column('salesJobPermitsEnteredByDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobPermitsUpdatedByDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobPermitsUpdatedByUserID', sa.String(length=255), nullable=False),
    sa.Column('salesJobPermitsNotes', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.ForeignKeyConstraint(['salesJobPermitsAssignedToID'], ['EmployeeMaster.employeeID'], ),
    sa.PrimaryKeyConstraint('salesJobPermitsID')
    )
    op.create_table('SalesJobServiceTicket',
    sa.Column('salesJobServiceTicketID', sa.UUID(), nullable=False),
    sa.Column('salesJobServiceTicketNumber', sa.Integer(), nullable=False),
    sa.Column('salesJobID', sa.UUID(), nullable=True),
    sa.Column('salesJobServiceTicketDescription', sa.String(length=255), nullable=False),
    sa.Column('salesJobServiceTicketCategory', sa.String(length=255), nullable=False),
    sa.Column('salesJobServiceTicketStatus', sa.Boolean(), nullable=False),
    sa.Column('salesJobServiceTicketStatusNotes', sa.String(length=255), nullable=False),
    sa.Column('salesJobServiceTicketBillable', sa.Boolean(), nullable=False),
    sa.Column('salesJobServiceTicketWarranty', sa.Boolean(), nullable=False),
    sa.Column('salesJobServiceTicketAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobServiceTicketAmountCustomerPaid', sa.String(length=255), nullable=False),
    sa.Column('salesJobServiceTicketAmountTransactionNumber', sa.String(length=255), nullable=False),
    sa.Column('salesJobServiceTicketAmountPaymentDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobServiceTicketPaid', sa.Boolean(), nullable=False),
    sa.Column('salesJobServiceTicketAssignToID', sa.UUID(), nullable=True),
    sa.Column('salesJobServiceTicketInstallerID', sa.UUID(), nullable=True),
    sa.Column('salesJobServiceTicketEnteredByID', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobID'], ['SalesJob.salesJobID'], ),
    sa.ForeignKeyConstraint(['salesJobServiceTicketAssignToID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobServiceTicketEnteredByID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobServiceTicketInstallerID'], ['SubContractor.subContractorID'], ),
    sa.PrimaryKeyConstraint('salesJobServiceTicketID')
    )
    op.create_table('EmployeePayDetail',
    sa.Column('employeePayDetailID', sa.UUID(), nullable=False),
    sa.Column('commissionReportID', sa.UUID(), nullable=True),
    sa.Column('payrollPeriodStartDate', sa.DateTime(), nullable=False),
    sa.Column('payrollPeriodEndDate', sa.DateTime(), nullable=False),
    sa.Column('payType', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commissionReportID'], ['CommissionReport.commissionReportID'], ),
    sa.PrimaryKeyConstraint('employeePayDetailID')
    )
    op.create_table('PayrollNotes',
    sa.Column('payrollNotesID', sa.UUID(), nullable=False),
    sa.Column('masterPayrollPeriodID', sa.UUID(), nullable=True),
    sa.Column('commissionReportID', sa.UUID(), nullable=True),
    sa.Column('payrollNotesExcelCreatedDate', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commissionReportID'], ['CommissionReport.commissionReportID'], ),
    sa.ForeignKeyConstraint(['masterPayrollPeriodID'], ['MasterPayrollPeriod.masterPayrollPeriodID'], ),
    sa.PrimaryKeyConstraint('payrollNotesID')
    )
    op.create_table('SalesJobFinancingCompany',
    sa.Column('salesJobFinancingCompanyID', sa.UUID(), nullable=False),
    sa.Column('salesJobFinancingID', sa.UUID(), nullable=True),
    sa.Column('salesJobFinancingCompanyName', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingCompanyAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingCompanyCreditLimit', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingCompanyMonths', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingCompanyFinancingPlan', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingCompanyLoanApprovalDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobFinancingCompanyLoanExpirationDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobFinancingCompanyCreditApproved', sa.Boolean(), nullable=False),
    sa.Column('salesJobFinancingCompanyCredit2ndLook', sa.Boolean(), nullable=False),
    sa.Column('salesJobFinancingCompanyCreditRate', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingCompanyCreditTerms', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobFinancingID'], ['SalesJobFinancing.salesJobFinancingID'], ),
    sa.PrimaryKeyConstraint('salesJobFinancingCompanyID')
    )
    op.create_table('SalesJobFinancingParty',
    sa.Column('salesJobFinancingPartyID', sa.UUID(), nullable=False),
    sa.Column('salesJobFinancingID', sa.UUID(), nullable=True),
    sa.Column('salesJobFinancingPartyName', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingPartyPhone', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingPartyEmployer', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingPartyCreditScore', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancingPartyAnnualIncome', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesJobFinancingID'], ['SalesJobFinancing.salesJobFinancingID'], ),
    sa.PrimaryKeyConstraint('salesJobFinancingPartyID')
    )
    op.create_table('SalesJobServiceTicketLogs',
    sa.Column('salesJobServiceTicketLogsID', sa.UUID(), nullable=False),
    sa.Column('salesJobServiceTicketID', sa.UUID(), nullable=True),
    sa.Column('salesJobServiceTicketLogsLogTitle', sa.String(length=255), nullable=False),
    sa.Column('salesJobServiceTicketLogsLogDetails', sa.String(length=255), nullable=False),
    sa.Column('employeeID', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobServiceTicketID'], ['SalesJobServiceTicket.salesJobServiceTicketID'], ),
    sa.PrimaryKeyConstraint('salesJobServiceTicketLogsID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SalesJobServiceTicketLogs')
    op.drop_table('SalesJobFinancingParty')
    op.drop_table('SalesJobFinancingCompany')
    op.drop_table('PayrollNotes')
    op.drop_table('EmployeePayDetail')
    op.drop_table('SalesJobServiceTicket')
    op.drop_table('SalesJobPermits')
    op.drop_table('SalesJobPayment')
    op.drop_table('SalesJobNotes')
    op.drop_table('SalesJobMilestoneDate')
    op.drop_table('SalesJobMaterialsOrdered')
    op.drop_table('SalesJobFinancing')
    op.drop_table('SalesJobCost')
    op.drop_table('SalesJobCommissions')
    op.drop_table('SalesJobAddendum')
    op.drop_table('EmployeePayrollBonus')
    op.drop_table('ContractLineItem')
    op.drop_table('CommissionReport')
    op.drop_table('SalesJobDocuments')
    op.drop_table('SalesJob')
    op.drop_table('EntityPropertyContact')
    op.drop_table('EntityCallback')
    op.drop_table('EntityAppointments')
    op.drop_table('SalesJobDocumentCategory')
    op.drop_table('EntitySecondaryContactDetails')
    op.drop_table('EntityProperty')
    op.drop_table('EntityCallCenterNotes')
    op.drop_table('EntityCall')
    op.drop_table('SubContractorEmployee')
    op.drop_table('SalesJobDocumentCategoryDocuments')
    op.drop_table('Entity')
    op.drop_table('SubContractor')
    op.drop_table('MaterialsVendor')
    op.drop_table('MasterPayrollPeriod')
    op.drop_table('EntitySelectedProduct')
    op.drop_table('EmployeeMaster')
    op.drop_table('ConstantsPropertyAppointmentState')
    op.drop_table('ConstantsProductType')
    op.drop_table('ConstantsMarketType')
    op.drop_table('ConstantsJobStatus')
    op.drop_table('BellemarBaseTable')
    # ### end Alembic commands ###
