"""EmployeeMster table removed

Revision ID: 6e67e9eb8492
Revises: 0765eb862cef
Create Date: 2024-12-10 12:05:04.703423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e67e9eb8492'
down_revision: Union[str, None] = '0765eb862cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CommissionReport_commissionReportDesignConsultanID_fkey', 'CommissionReport', type_='foreignkey')
    op.drop_column('CommissionReport', 'commissionReportDesignConsultanID')
    op.drop_constraint('Entity_entityInboundRecordLockedByID_fkey', 'Entity', type_='foreignkey')
    op.drop_constraint('Entity_entityAssignedTo_fkey', 'Entity', type_='foreignkey')
    op.drop_column('Entity', 'entityAssignedTo')
    op.drop_column('Entity', 'entityIniitialName')
    op.drop_column('Entity', 'entityInboundRecordLockedByID')
    op.drop_constraint('EntityAppointments_entityAppointmentsLeadSetterID_fkey', 'EntityAppointments', type_='foreignkey')
    op.drop_constraint('EntityAppointments_entityAppointmentsSalesRep1_fkey', 'EntityAppointments', type_='foreignkey')
    op.drop_constraint('EntityAppointments_entityAppointmentsSalesRep2_fkey', 'EntityAppointments', type_='foreignkey')
    op.drop_column('EntityAppointments', 'entityAppointmentsSalesRep2')
    op.drop_column('EntityAppointments', 'entityAppointmentsSalesRep1')
    op.drop_column('EntityAppointments', 'entityAppointmentsLeadSetterID')
    op.drop_constraint('EntityCall_entityCallCallerID_fkey', 'EntityCall', type_='foreignkey')
    op.drop_column('EntityCall', 'entityCallCallerID')
    op.drop_constraint('EntityCallback_entityCallbackAssignedTo_fkey', 'EntityCallback', type_='foreignkey')
    op.drop_column('EntityCallback', 'entityCallbackAssignedTo')
    op.drop_constraint('SalesJob_salesJobProjectManagerID_fkey', 'SalesJob', type_='foreignkey')
    op.drop_constraint('SalesJob_salesJobMeasuredByID_fkey', 'SalesJob', type_='foreignkey')
    op.drop_constraint('SalesJob_salesJobSalesPersonID_fkey', 'SalesJob', type_='foreignkey')
    op.drop_column('SalesJob', 'salesJobMeasuredByID')
    op.drop_column('SalesJob', 'salesJobSalesPersonID')
    op.drop_column('SalesJob', 'salesJobProjectManagerID')
    op.drop_constraint('SalesJobAddendum_salesJobAddendumDesignConsultantID_fkey', 'SalesJobAddendum', type_='foreignkey')
    op.drop_constraint('SalesJobAddendum_salesJobAddendumProjectManagerID_fkey', 'SalesJobAddendum', type_='foreignkey')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumDesignConsultantID')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumProjectManagerID')
    op.drop_constraint('SalesJobDocumentCategoryDocum_salesJobDocumentCategoryDocu_fkey', 'SalesJobDocumentCategoryDocuments', type_='foreignkey')
    op.drop_column('SalesJobDocumentCategoryDocuments', 'salesJobDocumentCategoryDocumentsUploadedByID')
    op.drop_constraint('SalesJobNotes_salesJobNotesEnteredOnUserID_fkey', 'SalesJobNotes', type_='foreignkey')
    op.drop_constraint('SalesJobNotes_salesJobNotesNotifyToID_fkey', 'SalesJobNotes', type_='foreignkey')
    op.drop_column('SalesJobNotes', 'salesJobNotesNotifyToID')
    op.drop_column('SalesJobNotes', 'salesJobNotesEnteredOnUserID')
    op.drop_constraint('SalesJobPayment_salesJobPaymentEnteredByID_fkey', 'SalesJobPayment', type_='foreignkey')
    op.drop_column('SalesJobPayment', 'salesJobPaymentEnteredByID')
    op.drop_constraint('SalesJobPermits_salesJobPermitsAssignedToID_fkey', 'SalesJobPermits', type_='foreignkey')
    op.drop_column('SalesJobPermits', 'salesJobPermitsAssignedToID')
    op.drop_constraint('SalesJobServiceTicket_salesJobServiceTicketAssignToID_fkey', 'SalesJobServiceTicket', type_='foreignkey')
    op.drop_constraint('SalesJobServiceTicket_salesJobServiceTicketEnteredByID_fkey', 'SalesJobServiceTicket', type_='foreignkey')
    op.drop_column('SalesJobServiceTicket', 'salesJobServiceTicketAssignToID')
    op.drop_column('SalesJobServiceTicket', 'salesJobServiceTicketEnteredByID')
    op.drop_constraint('SalesJobServiceTicketLogs_employeeID_fkey', 'SalesJobServiceTicketLogs', type_='foreignkey')
    op.drop_column('SalesJobServiceTicketLogs', 'employeeID')
    op.drop_constraint('SalesPersonAvailability_salesPersonID_fkey', 'SalesPersonAvailability', type_='foreignkey')
    op.drop_column('SalesPersonAvailability', 'salesPersonID')
    op.drop_table('EmployeeMaster')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SalesPersonAvailability', sa.Column('salesPersonID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesPersonAvailability_salesPersonID_fkey', 'SalesPersonAvailability', 'EmployeeMaster', ['salesPersonID'], ['employeeID'])
    op.add_column('SalesJobServiceTicketLogs', sa.Column('employeeID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobServiceTicketLogs_employeeID_fkey', 'SalesJobServiceTicketLogs', 'EmployeeMaster', ['employeeID'], ['employeeID'])
    op.add_column('SalesJobServiceTicket', sa.Column('salesJobServiceTicketEnteredByID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('SalesJobServiceTicket', sa.Column('salesJobServiceTicketAssignToID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobServiceTicket_salesJobServiceTicketEnteredByID_fkey', 'SalesJobServiceTicket', 'EmployeeMaster', ['salesJobServiceTicketEnteredByID'], ['employeeID'])
    op.create_foreign_key('SalesJobServiceTicket_salesJobServiceTicketAssignToID_fkey', 'SalesJobServiceTicket', 'EmployeeMaster', ['salesJobServiceTicketAssignToID'], ['employeeID'])
    op.add_column('SalesJobPermits', sa.Column('salesJobPermitsAssignedToID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobPermits_salesJobPermitsAssignedToID_fkey', 'SalesJobPermits', 'EmployeeMaster', ['salesJobPermitsAssignedToID'], ['employeeID'])
    op.add_column('SalesJobPayment', sa.Column('salesJobPaymentEnteredByID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobPayment_salesJobPaymentEnteredByID_fkey', 'SalesJobPayment', 'EmployeeMaster', ['salesJobPaymentEnteredByID'], ['employeeID'])
    op.add_column('SalesJobNotes', sa.Column('salesJobNotesEnteredOnUserID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('SalesJobNotes', sa.Column('salesJobNotesNotifyToID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobNotes_salesJobNotesNotifyToID_fkey', 'SalesJobNotes', 'EmployeeMaster', ['salesJobNotesNotifyToID'], ['employeeID'])
    op.create_foreign_key('SalesJobNotes_salesJobNotesEnteredOnUserID_fkey', 'SalesJobNotes', 'EmployeeMaster', ['salesJobNotesEnteredOnUserID'], ['employeeID'])
    op.add_column('SalesJobDocumentCategoryDocuments', sa.Column('salesJobDocumentCategoryDocumentsUploadedByID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobDocumentCategoryDocum_salesJobDocumentCategoryDocu_fkey', 'SalesJobDocumentCategoryDocuments', 'EmployeeMaster', ['salesJobDocumentCategoryDocumentsUploadedByID'], ['employeeID'])
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumProjectManagerID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumDesignConsultantID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobAddendum_salesJobAddendumProjectManagerID_fkey', 'SalesJobAddendum', 'EmployeeMaster', ['salesJobAddendumProjectManagerID'], ['employeeID'])
    op.create_foreign_key('SalesJobAddendum_salesJobAddendumDesignConsultantID_fkey', 'SalesJobAddendum', 'EmployeeMaster', ['salesJobAddendumDesignConsultantID'], ['employeeID'])
    op.add_column('SalesJob', sa.Column('salesJobProjectManagerID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('SalesJob', sa.Column('salesJobSalesPersonID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('SalesJob', sa.Column('salesJobMeasuredByID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJob_salesJobSalesPersonID_fkey', 'SalesJob', 'EmployeeMaster', ['salesJobSalesPersonID'], ['employeeID'])
    op.create_foreign_key('SalesJob_salesJobMeasuredByID_fkey', 'SalesJob', 'EmployeeMaster', ['salesJobMeasuredByID'], ['employeeID'])
    op.create_foreign_key('SalesJob_salesJobProjectManagerID_fkey', 'SalesJob', 'EmployeeMaster', ['salesJobProjectManagerID'], ['employeeID'])
    op.add_column('EntityCallback', sa.Column('entityCallbackAssignedTo', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('EntityCallback_entityCallbackAssignedTo_fkey', 'EntityCallback', 'EmployeeMaster', ['entityCallbackAssignedTo'], ['employeeID'])
    op.add_column('EntityCall', sa.Column('entityCallCallerID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('EntityCall_entityCallCallerID_fkey', 'EntityCall', 'EmployeeMaster', ['entityCallCallerID'], ['employeeID'])
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsLeadSetterID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsSalesRep1', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsSalesRep2', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('EntityAppointments_entityAppointmentsSalesRep2_fkey', 'EntityAppointments', 'EmployeeMaster', ['entityAppointmentsSalesRep2'], ['employeeID'])
    op.create_foreign_key('EntityAppointments_entityAppointmentsSalesRep1_fkey', 'EntityAppointments', 'EmployeeMaster', ['entityAppointmentsSalesRep1'], ['employeeID'])
    op.create_foreign_key('EntityAppointments_entityAppointmentsLeadSetterID_fkey', 'EntityAppointments', 'EmployeeMaster', ['entityAppointmentsLeadSetterID'], ['employeeID'])
    op.add_column('Entity', sa.Column('entityInboundRecordLockedByID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('Entity', sa.Column('entityIniitialName', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('Entity', sa.Column('entityAssignedTo', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('Entity_entityAssignedTo_fkey', 'Entity', 'EmployeeMaster', ['entityAssignedTo'], ['employeeID'])
    op.create_foreign_key('Entity_entityInboundRecordLockedByID_fkey', 'Entity', 'EmployeeMaster', ['entityInboundRecordLockedByID'], ['employeeID'])
    op.add_column('CommissionReport', sa.Column('commissionReportDesignConsultanID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('CommissionReport_commissionReportDesignConsultanID_fkey', 'CommissionReport', 'EmployeeMaster', ['commissionReportDesignConsultanID'], ['employeeID'])
    op.create_table('EmployeeMaster',
    sa.Column('employeeID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employeeBadgeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employeeFirstName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('employeeLastName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('employeeHireDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('employeeTerminationDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('employeeUserName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('employeePassword', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('employeeIsActive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('employeeTitle', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('employeeTypeID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employeePayTypeID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employeePayTypeID'], ['ConstantsEmployeePayType.constantsEmployeePayTypeID'], name='EmployeeMaster_employeePayTypeID_fkey'),
    sa.ForeignKeyConstraint(['employeeTypeID'], ['ConstantsEmployeeType.constantsEmployeeTypeID'], name='EmployeeMaster_employeeTypeID_fkey'),
    sa.PrimaryKeyConstraint('employeeID', name='EmployeeMaster_pkey')
    )
    # ### end Alembic commands ###
