"""EntityAppointment model updated

Revision ID: 6e987c995bd0
Revises: 5e8024e0bd1d
Create Date: 2024-11-18 15:32:39.410180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e987c995bd0'
down_revision: Union[str, None] = '5e8024e0bd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsIsHOA', sa.Boolean(), nullable=False))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsIsGoodWithPermits', sa.Boolean(), nullable=False))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsIsRentalProperty', sa.Boolean(), nullable=False))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsIsDecisionMakers', sa.Boolean(), nullable=False))
    op.drop_column('EntityAppointments', 'entityAppointmentsGoodWithPermits')
    op.drop_column('EntityAppointments', 'entityAppointmentsRentalProperty')
    op.drop_column('EntityAppointments', 'entityAppointmentsDecisionMakers')
    op.drop_column('EntityAppointments', 'entityAppointmentsHOA')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsHOA', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsDecisionMakers', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsRentalProperty', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsGoodWithPermits', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('EntityAppointments', 'entityAppointmentsIsDecisionMakers')
    op.drop_column('EntityAppointments', 'entityAppointmentsIsRentalProperty')
    op.drop_column('EntityAppointments', 'entityAppointmentsIsGoodWithPermits')
    op.drop_column('EntityAppointments', 'entityAppointmentsIsHOA')
    # ### end Alembic commands ###
