"""entity Appointmnet table updated

Revision ID: 719dc05fda6f
Revises: dcff47cb9c1f
Create Date: 2024-12-09 20:14:36.077824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719dc05fda6f'
down_revision: Union[str, None] = 'dcff47cb9c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Entity', 'entityEmployment')
    op.drop_column('Entity', 'entityContactPreference')
    op.drop_column('Entity', 'entityMartialStatus')
    op.drop_column('Entity', 'entityMarket')
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsSalesRep1IsAccepted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsSalesRep2IsAccepted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsSalesRep1ResponseDate', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsSalesRep2ResponseDate', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.drop_column('EntityPropertyContact', 'entityPropertyEmployment')
    op.drop_column('EntityPropertyContact', 'entityPropertyMartialStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EntityPropertyContact', sa.Column('entityPropertyMartialStatus', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EntityPropertyContact', sa.Column('entityPropertyEmployment', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('EntityAppointments', 'entityAppointmentsSalesRep2ResponseDate')
    op.drop_column('EntityAppointments', 'entityAppointmentsSalesRep1ResponseDate')
    op.drop_column('EntityAppointments', 'entityAppointmentsSalesRep2IsAccepted')
    op.drop_column('EntityAppointments', 'entityAppointmentsSalesRep1IsAccepted')
    op.add_column('Entity', sa.Column('entityMarket', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('Entity', sa.Column('entityMartialStatus', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('Entity', sa.Column('entityContactPreference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('Entity', sa.Column('entityEmployment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
