"""droping constants tables

Revision ID: 7bb10b87c3f3
Revises: b978bae29c35
Create Date: 2024-12-03 16:48:44.693287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bb10b87c3f3'
down_revision: Union[str, None] = 'b978bae29c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('EmployeeMaster_employeePayTypeID_fkey', 'EmployeeMaster', type_='foreignkey')
    op.drop_constraint('EmployeeMaster_employeeTypeID_fkey', 'EmployeeMaster', type_='foreignkey')
    op.drop_constraint('Entity_constantsMarketID_fkey', 'Entity', type_='foreignkey')
    op.drop_constraint('Entity_constantsProductID_fkey', 'Entity', type_='foreignkey')
    op.drop_constraint('EntityAppointments_constantsPropertyAppointmentStateID_fkey', 'EntityAppointments', type_='foreignkey')
    op.drop_constraint('EntityPhone_constantsPhoneTypeID_fkey', 'EntityPhone', type_='foreignkey')
    op.drop_constraint('SalesJob_salesJobStatusID_fkey', 'SalesJob', type_='foreignkey')
    op.drop_constraint('SubContractor_subContractorMarketID_fkey', 'SubContractor', type_='foreignkey')
    op.drop_column('EmployeeMaster', 'employeePayTypeID')
    op.drop_column('EmployeeMaster', 'employeeTypeID')
    op.drop_column('Entity', 'constantsProductID')
    op.drop_column('Entity', 'constantsMarketID')
    op.drop_column('EntityAppointments', 'constantsPropertyAppointmentStateID')
    op.drop_column('EntityPhone', 'constantsPhoneTypeID')
    op.drop_column('SalesJob', 'salesJobStatusID')
    op.drop_column('SubContractor', 'subContractorMarketID')
    op.drop_table('ConstantsMarketType')
    op.drop_table('ConstantsPropertyAppointmentState')
    op.drop_table('ConstantsPhoneType')
    op.drop_table('ConstantsEntityMaritalStatus')
    op.drop_table('ConstantsPropertyLookUp')
    op.drop_table('ConstantsEntitySubSource')
    op.drop_table('ConstantsEntitySource')
    op.drop_table('ConstantsEmployeePayType')
    op.drop_table('ConstantsEntityEmploymentStatus')
    op.drop_table('ConstantsEmployeeType')
    op.drop_table('ConstantsProductType')
    op.drop_table('ConstantsEntityPropertyStructure')
    op.drop_table('ConstantsJobStatus')
    op.drop_table('ConstantsEntityCallType')
    op.drop_table('ConstantsEntityCallResult')
    # # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SubContractor', sa.Column('subContractorMarketID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SubContractor_subContractorMarketID_fkey', 'SubContractor', 'ConstantsMarketType', ['subContractorMarketID'], ['constantsMarketID'])
    op.add_column('SalesJob', sa.Column('salesJobStatusID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJob_salesJobStatusID_fkey', 'SalesJob', 'ConstantsJobStatus', ['salesJobStatusID'], ['constantsJobStatusID'])
    op.add_column('EntityPhone', sa.Column('constantsPhoneTypeID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('EntityPhone_constantsPhoneTypeID_fkey', 'EntityPhone', 'ConstantsPhoneType', ['constantsPhoneTypeID'], ['constantsPhoneTypeID'])
    op.add_column('EntityAppointments', sa.Column('constantsPropertyAppointmentStateID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('EntityAppointments_constantsPropertyAppointmentStateID_fkey', 'EntityAppointments', 'ConstantsPropertyAppointmentState', ['constantsPropertyAppointmentStateID'], ['constantsPropertyAppointmentStateID'])
    op.add_column('Entity', sa.Column('constantsMarketID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('Entity', sa.Column('constantsProductID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('Entity_constantsProductID_fkey', 'Entity', 'ConstantsProductType', ['constantsProductID'], ['constantsProductID'])
    op.create_foreign_key('Entity_constantsMarketID_fkey', 'Entity', 'ConstantsMarketType', ['constantsMarketID'], ['constantsMarketID'])
    op.add_column('EmployeeMaster', sa.Column('employeeTypeID', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('EmployeeMaster', sa.Column('employeePayTypeID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('EmployeeMaster_employeeTypeID_fkey', 'EmployeeMaster', 'ConstantsEmployeeType', ['employeeTypeID'], ['constantsEmployeeTypeID'])
    op.create_foreign_key('EmployeeMaster_employeePayTypeID_fkey', 'EmployeeMaster', 'ConstantsEmployeePayType', ['employeePayTypeID'], ['constantsEmployeePayTypeID'])
    op.create_table('ConstantsEntityCallResult',
    sa.Column('constantsEntityCallResultID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsEntityCallResultName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityCallResultID', name='ConstantsEntityCallResult_pkey')
    )
    op.create_table('ConstantsEntitySubSource',
    sa.Column('constantsEntitySubSourceID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsEntitySubSourceName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('constantsEntitySourceID', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['constantsEntitySourceID'], ['ConstantsEntitySource.constantsEntitySourceID'], name='ConstantsEntitySubSource_constantsEntitySourceID_fkey'),
    sa.PrimaryKeyConstraint('constantsEntitySubSourceID', name='ConstantsEntitySubSource_pkey')
    )
    op.create_table('ConstantsEntityCallType',
    sa.Column('constantsEntityCallTypeID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsEntityCallTypeName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityCallTypeID', name='ConstantsEntityCallType_pkey')
    )
    op.create_table('ConstantsJobStatus',
    sa.Column('constantsJobStatusID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsJobStatusName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsJobStatusID', name='ConstantsJobStatus_pkey')
    )
    op.create_table('ConstantsEntityPropertyStructure',
    sa.Column('constantsEntityPropertyStructureID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsEntityPropertyStructureName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityPropertyStructureID', name='ConstantsEntityPropertyStructure_pkey')
    )
    op.create_table('ConstantsProductType',
    sa.Column('constantsProductID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsProductName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsProductID', name='ConstantsProductType_pkey')
    )
    op.create_table('ConstantsEmployeeType',
    sa.Column('constantsEmployeeTypeID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsEmployeeTypeName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsEmployeeTypeID', name='ConstantsEmployeeType_pkey')
    )
    op.create_table('ConstantsEntityEmploymentStatus',
    sa.Column('constantsEntityEmploymentStatusID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsEntityEmploymentStatusName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityEmploymentStatusID', name='ConstantsEntityEmploymentStatus_pkey')
    )
    op.create_table('ConstantsEmployeePayType',
    sa.Column('constantsEmployeePayTypeID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsEmployeePayTypeName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsEmployeePayTypeID', name='ConstantsEmployeePayType_pkey')
    )
    op.create_table('ConstantsEntitySource',
    sa.Column('constantsEntitySourceID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsEntitySourceName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsEntitySourceID', name='ConstantsEntitySource_pkey')
    )
    op.create_table('ConstantsPropertyLookUp',
    sa.Column('constantsPropertyLookUpID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsPropertyLookUpName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('constantsPropertyLookUpLink', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsPropertyLookUpID', name='ConstantsPropertyLookUp_pkey')
    )
    op.create_table('ConstantsEntityMaritalStatus',
    sa.Column('constantsEntityMaritalStatusID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsEntityMaritalStatusName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityMaritalStatusID', name='ConstantsEntityMaritalStatus_pkey')
    )
    op.create_table('ConstantsPhoneType',
    sa.Column('constantsPhoneTypeID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsPhoneTypeName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsPhoneTypeID', name='ConstantsPhoneType_pkey')
    )
    op.create_table('ConstantsPropertyAppointmentState',
    sa.Column('constantsPropertyAppointmentStateID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsPropertyState', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('constantsAppointmentState', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('constantsAppointmentStateDescription', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsPropertyAppointmentStateID', name='ConstantsPropertyAppointmentState_pkey')
    )
    op.create_table('ConstantsMarketType',
    sa.Column('constantsMarketID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('constantsMarketName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('constantsMarketID', name='ConstantsMarketType_pkey')
    )
    # ### end Alembic commands ###
