"""ConstantsVoucherType table added

Revision ID: 8038c4c3103a
Revises: 9f1ac981a47d
Create Date: 2024-12-12 10:48:25.552197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8038c4c3103a'
down_revision: Union[str, None] = '9f1ac981a47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConstantsUSAStates',
    sa.Column('constantsUSAStatesID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsUSAStatesName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsUSAStatesID')
    )
    op.create_table('ConstantsVoucherType',
    sa.Column('constantsVoucherTypeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsVoucherType', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsVoucherTypeID')
    )
    op.drop_constraint('SalesJob_salesJobSubContractorID_fkey', 'SalesJob', type_='foreignkey')
    op.drop_column('SalesJob', 'salesJobSubContractorID')
    op.drop_constraint('SalesJobServiceTicket_salesJobServiceTicketInstallerID_fkey', 'SalesJobServiceTicket', type_='foreignkey')
    op.drop_column('SalesJobServiceTicket', 'salesJobServiceTicketInstallerID')
    op.drop_table('SubContractorInstaller')
    op.drop_table('SubContractor')
    op.drop_table('ConsantsUSAStates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SalesJobServiceTicket', sa.Column('salesJobServiceTicketInstallerID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobServiceTicket_salesJobServiceTicketInstallerID_fkey', 'SalesJobServiceTicket', 'SubContractor', ['salesJobServiceTicketInstallerID'], ['subContractorID'])
    op.add_column('SalesJob', sa.Column('salesJobSubContractorID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJob_salesJobSubContractorID_fkey', 'SalesJob', 'SubContractor', ['salesJobSubContractorID'], ['subContractorID'])
    op.create_table('ConsantsUSAStates',
    sa.Column('consantsUSAStatesID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('consantsUSAStatesName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('consantsUSAStatesID', name='ConsantsUSAStates_pkey')
    )
    op.create_table('SubContractor',
    sa.Column('subContractorID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyAddressLine1', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyAddressLine2', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyCity', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyState', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyZipCode', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyPhone', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyEmail', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyLicenseNumber', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorOwnerFirsttName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorOwnerLastName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyOwnerPhone', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorCompanyOwnerEmail', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='statusenum'), autoincrement=False, nullable=False),
    sa.Column('subContractorMarketID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subContractorMarketID'], ['ConstantsMarketType.constantsMarketID'], name='SubContractor_subContractorMarketID_fkey'),
    sa.PrimaryKeyConstraint('subContractorID', name='SubContractor_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('SubContractorInstaller',
    sa.Column('subContractorInstallerID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subContractorID', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subContractorInstallerFirstName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorInstallerLastName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorInstallerPhone', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorInstallerEmail', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='statusenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subContractorID'], ['SubContractor.subContractorID'], name='SubContractorInstaller_subContractorID_fkey'),
    sa.PrimaryKeyConstraint('subContractorInstallerID', name='SubContractorInstaller_pkey')
    )
    op.drop_table('ConstantsVoucherType')
    op.drop_table('ConstantsUSAStates')
    # ### end Alembic commands ###
