"""Entity and commission report updated

Revision ID: 91a3cdbee22b
Revises: d5bc0134203c
Create Date: 2024-11-22 15:50:21.007511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '91a3cdbee22b'
down_revision: Union[str, None] = 'd5bc0134203c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CommissionReport', sa.Column('commissionReportS3URL', sa.String(length=255), nullable=True))
    op.add_column('Entity', sa.Column('entityInboundRecordIsLocked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('Entity', sa.Column('entityInboundRecordLockedBy', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneContractDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneMeasureEstimatedDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneMeasureActualDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneOrderEstimatedDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneOrderActualDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneShipEstimatedDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneShipActualDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneStartEstimatedDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneStartActualDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestonePartOrderEstimatedDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestonePartOrderActualDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneCompletionEstimatedDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneCompletionActualDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneCancellationDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneHoldDate', sa.DateTime(), nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneHoldReason', sa.String(length=255), nullable=False))
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneDateName')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneDateActualDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneDatePlannedDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneDatePlannedDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneDateActualDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobMilestoneDateName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneHoldReason')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneHoldDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneCancellationDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneCompletionActualDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneCompletionEstimatedDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestonePartOrderActualDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestonePartOrderEstimatedDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneStartActualDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneStartEstimatedDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneShipActualDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneShipEstimatedDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneOrderActualDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneOrderEstimatedDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneMeasureActualDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneMeasureEstimatedDate')
    op.drop_column('SalesJobMilestoneDate', 'salesJobMilestoneContractDate')
    op.drop_column('Entity', 'entityInboundRecordLockedBy')
    op.drop_column('Entity', 'entityInboundRecordIsLocked')
    op.drop_column('CommissionReport', 'commissionReportS3URL')
    # ### end Alembic commands ###
