"""EntityDispute table updated>

Revision ID: 9f1ac981a47d
Revises: f0b2af430be4
Create Date: 2024-12-11 11:11:48.436592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f1ac981a47d'
down_revision: Union[str, None] = 'f0b2af430be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SubContractorInstaller',
    sa.Column('subContractorInstallerID', sa.UUID(), nullable=False),
    sa.Column('subContractorID', sa.UUID(), nullable=True),
    sa.Column('subContractorInstallerFirstName', sa.String(length=255), nullable=False),
    sa.Column('subContractorInstallerLastName', sa.String(length=255), nullable=False),
    sa.Column('subContractorInstallerPhone', sa.String(length=255), nullable=False),
    sa.Column('subContractorInstallerEmail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subContractorID'], ['SubContractor.subContractorID'], ),
    sa.PrimaryKeyConstraint('subContractorInstallerID')
    )
    op.drop_table('SubContractorEmployee')
    op.add_column('EntityDispute', sa.Column('entityDisputeOriginalSource', sa.String(length=255), nullable=False, server_default=""))
    op.add_column('EntityDispute', sa.Column('entityDisputeOriginalSubSource', sa.String(length=255), nullable=False, server_default=""))
    op.add_column('SubContractorInstaller', sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='statusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EntityDispute', 'entityDisputeOriginalSubSource')
    op.drop_column('EntityDispute', 'entityDisputeOriginalSource')
    op.create_table('SubContractorEmployee',
    sa.Column('subContractorEmployeeID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subContractorID', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subContractorEmployeeFirstName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorEmployeeLastName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorEmployeePhone', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subContractorEmployeeEmail', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='statusenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subContractorID'], ['SubContractor.subContractorID'], name='SubContractorEmployee_subContractorID_fkey'),
    sa.PrimaryKeyConstraint('subContractorEmployeeID', name='SubContractorEmployee_pkey')
    )
    op.drop_table('SubContractorInstaller')
    # ### end Alembic commands ###
