"""Entity, Commission_report and,SalesJobAddendum updated

Revision ID: a38a72254696
Revises: add37af324bd
Create Date: 2024-12-16 12:52:00.921376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a38a72254696'
down_revision: Union[str, None] = 'add37af324bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CommissionReport', sa.Column('commissionReportSoldByID', sa.Integer(), nullable=True))
    op.add_column('CommissionReport', sa.Column('commissionReportTotalCommissionOnNonCommercialItemsPercent', sa.String(length=255), nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportNotesToDesignConsultant', sa.String(length=255), nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportIsDeleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('CommissionReport', 'commissionReportRevisedContractPrice',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('CommissionReport', 'commissionReportTotalCommissionPrice',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('CommissionReport', 'commissionReportExpectedPrepayCommissionPrice',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('CommissionReport', 'commissionReportExpectedFinalCommissionPrice',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('CommissionReport', 'commissionReportNotes',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('CommissionReport', 'commissionReportS3URL',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('CommissionReport_commissionReportDesignConsultanID_fkey', 'CommissionReport', type_='foreignkey')
    op.create_foreign_key(None, 'CommissionReport', 'EmployeeMaster', ['commissionReportSoldByID'], ['employeeID'])
    op.drop_column('CommissionReport', 'commissionReportCustomerEmail1')
    op.drop_column('CommissionReport', 'commissionReportDesignConsultanID')
    op.drop_column('CommissionReport', 'commissionReportCustomerPhone1')
    op.drop_column('CommissionReport', 'commissionReportDesignConsultantName')
    op.drop_column('CommissionReport', 'commissionReportCustomerEmail3')
    op.drop_column('CommissionReport', 'commissionReportCustomerState')
    op.drop_column('CommissionReport', 'commissionReportCustomerZip')
    op.drop_column('CommissionReport', 'commissionReportCustomerEmail2')
    op.drop_column('CommissionReport', 'commissionReportTotalCommissionOnNonCommercialItems')
    op.drop_column('CommissionReport', 'commissionReportCustomerCity')
    op.drop_column('CommissionReport', 'commissionReportCustomerAddressLine2')
    op.drop_column('CommissionReport', 'commissionReportCustomerName')
    op.drop_column('CommissionReport', 'commissionReportCustomerAddressLine1')
    op.drop_column('CommissionReport', 'commissionReportCustomerPhone2')
    op.add_column('EmployeePayDetail', sa.Column('employePayDetailEmployeeID', sa.Integer(), nullable=True))
    op.add_column('EmployeePayDetail', sa.Column('employeePayDetailPayrollPeriodStartDate', sa.DateTime(), nullable=False))
    op.add_column('EmployeePayDetail', sa.Column('employeePayDetailPayrollPeriodEndDate', sa.DateTime(), nullable=False))
    op.add_column('EmployeePayDetail', sa.Column('employeePayDetailCustomerFullName', sa.String(length=255), nullable=False))
    op.add_column('EmployeePayDetail', sa.Column('employeePayDetailCustomerAddress', sa.String(length=255), nullable=False))
    op.add_column('EmployeePayDetail', sa.Column('employeePayDetailCommissionTypePrepay', sa.String(length=255), nullable=False))
    op.add_column('EmployeePayDetail', sa.Column('employeePayDetailCommissionTypeFinal', sa.String(length=255), nullable=False))
    op.add_column('EmployeePayDetail', sa.Column('employeePayDetailCommissionTypeAddendum', sa.String(length=255), nullable=False))
    op.add_column('EmployeePayDetail', sa.Column('salesJobAddendumID', sa.UUID(), nullable=True))
    op.add_column('EmployeePayDetail', sa.Column('employeePayDetailTotalCommission', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'EmployeePayDetail', 'EmployeeMaster', ['employePayDetailEmployeeID'], ['employeeID'])
    op.create_foreign_key(None, 'EmployeePayDetail', 'SalesJobAddendum', ['salesJobAddendumID'], ['salesJobAddendumID'])
    op.drop_column('EmployeePayDetail', 'payrollPeriodEndDate')
    op.drop_column('EmployeePayDetail', 'payrollPeriodStartDate')
    op.add_column('Entity', sa.Column('constantsMarketID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Entity', 'ConstantsMarketType', ['constantsMarketID'], ['constantsMarketID'])
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumSoldByID', sa.Integer(), nullable=True))
    op.drop_constraint('SalesJobAddendum_salesJobAddendumDesignConsultantID_fkey', 'SalesJobAddendum', type_='foreignkey')
    op.drop_constraint('SalesJobAddendum_salesJobAddendumProjectManagerID_fkey', 'SalesJobAddendum', type_='foreignkey')
    op.create_foreign_key(None, 'SalesJobAddendum', 'EmployeeMaster', ['salesJobAddendumSoldByID'], ['employeeID'])
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerAddressLine1')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerEmail3')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerZip')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerName')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerCity')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumPositiveCommissionAmount')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumDesignConsultantID')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerState')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerAddressLine2')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerEmail1')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerPhone2')
    op.drop_column('SalesJobAddendum', 'created_at')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerPhone1')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumProjectManagerID')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumCustomerEmail2')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumDesignConsultantName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumDesignConsultantName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerEmail2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumProjectManagerID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerPhone1', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerPhone2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerEmail1', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerAddressLine2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerState', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumDesignConsultantID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumPositiveCommissionAmount', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerCity', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerZip', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerEmail3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumCustomerAddressLine1', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'SalesJobAddendum', type_='foreignkey')
    op.create_foreign_key('SalesJobAddendum_salesJobAddendumProjectManagerID_fkey', 'SalesJobAddendum', 'EmployeeMaster', ['salesJobAddendumProjectManagerID'], ['employeeID'])
    op.create_foreign_key('SalesJobAddendum_salesJobAddendumDesignConsultantID_fkey', 'SalesJobAddendum', 'EmployeeMaster', ['salesJobAddendumDesignConsultantID'], ['employeeID'])
    op.drop_column('SalesJobAddendum', 'salesJobAddendumSoldByID')
    op.drop_constraint(None, 'Entity', type_='foreignkey')
    op.drop_column('Entity', 'constantsMarketID')
    op.add_column('EmployeePayDetail', sa.Column('payrollPeriodStartDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('EmployeePayDetail', sa.Column('payrollPeriodEndDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EmployeePayDetail', type_='foreignkey')
    op.drop_constraint(None, 'EmployeePayDetail', type_='foreignkey')
    op.drop_column('EmployeePayDetail', 'employeePayDetailTotalCommission')
    op.drop_column('EmployeePayDetail', 'salesJobAddendumID')
    op.drop_column('EmployeePayDetail', 'employeePayDetailCommissionTypeAddendum')
    op.drop_column('EmployeePayDetail', 'employeePayDetailCommissionTypeFinal')
    op.drop_column('EmployeePayDetail', 'employeePayDetailCommissionTypePrepay')
    op.drop_column('EmployeePayDetail', 'employeePayDetailCustomerAddress')
    op.drop_column('EmployeePayDetail', 'employeePayDetailCustomerFullName')
    op.drop_column('EmployeePayDetail', 'employeePayDetailPayrollPeriodEndDate')
    op.drop_column('EmployeePayDetail', 'employeePayDetailPayrollPeriodStartDate')
    op.drop_column('EmployeePayDetail', 'employePayDetailEmployeeID')
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerPhone2', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerAddressLine1', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerName', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerAddressLine2', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerCity', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportTotalCommissionOnNonCommercialItems', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerEmail2', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerZip', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerState', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerEmail3', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.add_column('CommissionReport', sa.Column('commissionReportDesignConsultantName', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerPhone1', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('CommissionReport', sa.Column('commissionReportDesignConsultanID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('CommissionReport', sa.Column('commissionReportCustomerEmail1', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'CommissionReport', type_='foreignkey')
    op.create_foreign_key('CommissionReport_commissionReportDesignConsultanID_fkey', 'CommissionReport', 'EmployeeMaster', ['commissionReportDesignConsultanID'], ['employeeID'])
    op.alter_column('CommissionReport', 'commissionReportS3URL',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('CommissionReport', 'commissionReportNotes',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('CommissionReport', 'commissionReportExpectedFinalCommissionPrice',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)
    op.alter_column('CommissionReport', 'commissionReportExpectedPrepayCommissionPrice',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)
    op.alter_column('CommissionReport', 'commissionReportTotalCommissionPrice',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)
    op.alter_column('CommissionReport', 'commissionReportRevisedContractPrice',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)
    op.drop_column('CommissionReport', 'commissionReportIsDeleted')
    op.drop_column('CommissionReport', 'commissionReportNotesToDesignConsultant')
    op.drop_column('CommissionReport', 'commissionReportTotalCommissionOnNonCommercialItemsPercent')
    op.drop_column('CommissionReport', 'commissionReportSoldByID')
    # ### end Alembic commands ###
