"""entity and entityAppointment updated

Revision ID: acbdacfee44a
Revises: 98af85cb0800
Create Date: 2024-12-18 16:21:31.178794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acbdacfee44a'
down_revision: Union[str, None] = '98af85cb0800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Entity', sa.Column('entityInitialDataReceivedProduct', sa.String(length=255), nullable=False, server_default=""))
    op.drop_constraint('Entity_entityAssignedTo_fkey', 'Entity', type_='foreignkey')
    op.drop_column('Entity', 'entityDoNotCall')
    op.drop_column('Entity', 'entityrDoNotText')
    op.drop_column('Entity', 'entityAssignedTo')
    op.drop_column('Entity', 'entityDoNotEmail')
    op.drop_column('EntityAppointments', 'status')
    op.add_column('SalesJob', sa.Column('salesJobStatusDispositionID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJob', 'ConstantsSalesJobDispositon', ['salesJobStatusDispositionID'], ['constantsSalesJobDispositonID'])
    op.add_column('SalesPersonAvailability', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('SalesPersonAvailabilitySlots', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SalesPersonAvailabilitySlots', 'created_at')
    op.drop_column('SalesPersonAvailability', 'created_at')
    op.drop_constraint(None, 'SalesJob', type_='foreignkey')
    op.drop_column('SalesJob', 'salesJobStatusDispositionID')
    op.add_column('EntityAppointments', sa.Column('status', postgresql.ENUM('Completed', 'On Hold', 'In Progress', name='appointmentenum'), server_default=sa.text("'On Hold'::appointmentenum"), autoincrement=False, nullable=False))
    op.add_column('Entity', sa.Column('entityDoNotEmail', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('Entity', sa.Column('entityAssignedTo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Entity', sa.Column('entityrDoNotText', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('Entity', sa.Column('entityDoNotCall', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('Entity_entityAssignedTo_fkey', 'Entity', 'EmployeeMaster', ['entityAssignedTo'], ['employeeID'])
    op.drop_column('Entity', 'entityInitialDataReceivedProduct')
    # ### end Alembic commands ###
