"""SalesJob created and modified

Revision ID: add37af324bd
Revises: bd6f4e0e81d1
Create Date: 2024-12-13 12:04:28.799989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add37af324bd'
down_revision: Union[str, None] = 'bd6f4e0e81d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SalesJob',
    sa.Column('salesJobID', sa.UUID(), nullable=False),
    sa.Column('salesJobNumber', sa.Integer(), nullable=False),
    sa.Column('salesJobEntityAppointmentNumber', sa.Integer(), nullable=False),
    sa.Column('salesJobEntityCustomerRecordNumber', sa.Integer(), nullable=False),
    sa.Column('entityPropertyID', sa.UUID(), nullable=True),
    sa.Column('salesJobContractDate', sa.DateTime(), nullable=False),
    sa.Column('salesJobSalesRepID', sa.Integer(), nullable=True),
    sa.Column('salesJobContractAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobFinancedAmount', sa.String(length=255), nullable=False),
    sa.Column('salesJobIsPermitRequired', sa.Boolean(), nullable=False),
    sa.Column('salesJobDiscountPercentage', sa.String(length=255), nullable=True),
    sa.Column('salesJobAdjustedContractValue', sa.String(length=255), nullable=True),
    sa.Column('salesJobVoucherTypeID', sa.Integer(), nullable=True),
    sa.Column('salesJobVoucherSentDate', sa.DateTime(), nullable=True),
    sa.Column('salesJobIsHOAAppRequired', sa.Boolean(), nullable=False),
    sa.Column('salesJobIsQualityControlled', sa.Boolean(), nullable=False),
    sa.Column('salesJobSubContractorID', sa.Integer(), nullable=True),
    sa.Column('salesJobSubContractorInstaller1ID', sa.Integer(), nullable=True),
    sa.Column('salesJobSubContractorInstaller2ID', sa.Integer(), nullable=True),
    sa.Column('salesJobProjectManager1ID', sa.Integer(), nullable=True),
    sa.Column('salesJobProjectManager2ID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityPropertyID'], ['EntityProperty.entityPropertyID'], ),
    sa.ForeignKeyConstraint(['salesJobProjectManager1ID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobProjectManager2ID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobSalesRepID'], ['EmployeeMaster.employeeID'], ),
    sa.ForeignKeyConstraint(['salesJobSubContractorID'], ['SubContractor.subContractorID'], ),
    sa.ForeignKeyConstraint(['salesJobSubContractorInstaller1ID'], ['SubContractorInstaller.subContractorInstallerID'], ),
    sa.ForeignKeyConstraint(['salesJobSubContractorInstaller2ID'], ['SubContractorInstaller.subContractorInstallerID'], ),
    sa.ForeignKeyConstraint(['salesJobVoucherTypeID'], ['ConstantsVoucherType.constantsVoucherTypeID'], ),
    sa.PrimaryKeyConstraint('salesJobID')
    )
    op.add_column('CommissionReport', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'CommissionReport', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('ContractLineItem', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ContractLineItem', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('EmployeePayrollBonus', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'EmployeePayrollBonus', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobAddendum', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobAddendum', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobCommissions', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobCommissions', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobCost', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobCost', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobDocuments', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobDocuments', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobFinancing', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobFinancing', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobMaterialsOrdered', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobMaterialsOrdered', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobMilestoneDate', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobNotes', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobNotes', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobPayment', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobPayment', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobPermits', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobPermits', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobServiceTicket', sa.Column('salesJobID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SalesJobServiceTicket', 'SalesJob', ['salesJobID'], ['salesJobID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SalesJobServiceTicket', type_='foreignkey')
    op.drop_column('SalesJobServiceTicket', 'salesJobID')
    op.drop_constraint(None, 'SalesJobPermits', type_='foreignkey')
    op.drop_column('SalesJobPermits', 'salesJobID')
    op.drop_constraint(None, 'SalesJobPayment', type_='foreignkey')
    op.drop_column('SalesJobPayment', 'salesJobID')
    op.drop_constraint(None, 'SalesJobNotes', type_='foreignkey')
    op.drop_column('SalesJobNotes', 'salesJobID')
    op.drop_constraint(None, 'SalesJobMilestoneDate', type_='foreignkey')
    op.drop_column('SalesJobMilestoneDate', 'salesJobID')
    op.drop_constraint(None, 'SalesJobMaterialsOrdered', type_='foreignkey')
    op.drop_column('SalesJobMaterialsOrdered', 'salesJobID')
    op.drop_constraint(None, 'SalesJobFinancing', type_='foreignkey')
    op.drop_column('SalesJobFinancing', 'salesJobID')
    op.drop_constraint(None, 'SalesJobDocuments', type_='foreignkey')
    op.drop_column('SalesJobDocuments', 'salesJobID')
    op.drop_constraint(None, 'SalesJobCost', type_='foreignkey')
    op.drop_column('SalesJobCost', 'salesJobID')
    op.drop_constraint(None, 'SalesJobCommissions', type_='foreignkey')
    op.drop_column('SalesJobCommissions', 'salesJobID')
    op.drop_constraint(None, 'SalesJobAddendum', type_='foreignkey')
    op.drop_column('SalesJobAddendum', 'salesJobID')
    op.drop_constraint(None, 'EmployeePayrollBonus', type_='foreignkey')
    op.drop_column('EmployeePayrollBonus', 'salesJobID')
    op.drop_constraint(None, 'ContractLineItem', type_='foreignkey')
    op.drop_column('ContractLineItem', 'salesJobID')
    op.drop_constraint(None, 'CommissionReport', type_='foreignkey')
    op.drop_column('CommissionReport', 'salesJobID')
    op.drop_table('SalesJob')
    # ### end Alembic commands ###
