"""made fields nullable=true in entity, appointmnet , property

Revision ID: b1b85552d9c9
Revises: 119ad33119da
Create Date: 2024-12-19 12:34:19.877209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1b85552d9c9'
down_revision: Union[str, None] = '119ad33119da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Entity', 'entityInboundRecordNumber',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Entity', 'entityInboundRecordStatus',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Entity', 'entityIsInboundDuplicateRecord',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Entity', 'entityIsInboundRecordMerged',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Entity', 'entityIsInboundRecordDeleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Entity', 'entityPermanentAddressLine1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Entity', 'entityPermanentCity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Entity', 'entityPermanentState',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Entity', 'entityPermanentZipcode',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Entity', 'entityInitialDataReceivedDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Entity', 'entityInitialDataReceivedProduct',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('EntityAppointments', 'entityAppointmentNumber',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('EntityAppointments', 'entityAppointmentsIssued',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('EntityAppointments', 'entityAppointmentsBCICallID',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('EntityAppointments', 'entityAppointmentsIsRentalProperty',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('EntityAppointments', 'entityAppointmentsIsDecisionMakers',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('EntityAppointments', 'entityAppointmentsSalesRep1IsAccepted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('EntityAppointments', 'entityAppointmentsSalesRep2IsAccepted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('EntityAppointments', 'entityAppointmentsSalesRep1ResponseDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('EntityAppointments', 'entityAppointmentsSalesRep2ResponseDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('EntityPropertyContact', 'entityPropertyContactPrefix',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Entity', 'entityInitialDataReceivedProduct',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('Entity', 'entityInitialDataReceivedDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Entity', 'entityPermanentZipcode',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Entity', 'entityPermanentState',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Entity', 'entityPermanentCity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Entity', 'entityPermanentAddressLine1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Entity', 'entityIsInboundRecordDeleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Entity', 'entityIsInboundRecordMerged',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Entity', 'entityIsInboundDuplicateRecord',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Entity', 'entityInboundRecordStatus',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Entity', 'entityInboundRecordNumber',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('EntityPropertyContact', 'entityPropertyContactPrefix',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentsSalesRep2ResponseDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('EntityAppointments', 'entityAppointmentsSalesRep1ResponseDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('EntityAppointments', 'entityAppointmentsSalesRep2IsAccepted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('EntityAppointments', 'entityAppointmentsSalesRep1IsAccepted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('EntityAppointments', 'entityAppointmentsIsDecisionMakers',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentsIsRentalProperty',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentsBCICallID',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentsIssued',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('EntityAppointments', 'entityAppointmentNumber',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
