"""new constants models are created

Revision ID: b978bae29c35
Revises: 27542fb80df5
Create Date: 2024-12-02 13:08:35.149620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b978bae29c35'
down_revision: Union[str, None] = '27542fb80df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConstantsEntityCallResult',
    sa.Column('constantsEntityCallResultID', sa.UUID(), nullable=False),
    sa.Column('constantsEntityCallResultName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityCallResultID')
    )
    op.create_table('ConstantsEntityCallType',
    sa.Column('constantsEntityCallTypeID', sa.UUID(), nullable=False),
    sa.Column('constantsEntityCallTypeName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityCallTypeID')
    )
    op.create_table('ConstantsEntityEmploymentStatus',
    sa.Column('constantsEntityEmploymentStatusID', sa.UUID(), nullable=False),
    sa.Column('constantsEntityEmploymentStatusName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityEmploymentStatusID')
    )
    op.create_table('ConstantsEntityMaritalStatus',
    sa.Column('constantsEntityMaritalStatusID', sa.UUID(), nullable=False),
    sa.Column('constantsEntityMaritalStatusName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityMaritalStatusID')
    )
    op.create_table('ConstantsEntityPropertyStructure',
    sa.Column('constantsEntityPropertyStructureID', sa.UUID(), nullable=False),
    sa.Column('constantsEntityPropertyStructureName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntityPropertyStructureID')
    )
    op.create_table('ConstantsEntitySource',
    sa.Column('constantsEntitySourceID', sa.UUID(), nullable=False),
    sa.Column('constantsEntitySourceName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEntitySourceID')
    )
    op.create_table('ConstantsPhoneType',
    sa.Column('constantsPhoneTypeID', sa.UUID(), nullable=False),
    sa.Column('constantsPhoneTypeName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsPhoneTypeID')
    )
    op.create_table('ConstantsPropertyLookUp',
    sa.Column('constantsPropertyLookUpID', sa.UUID(), nullable=False),
    sa.Column('constantsPropertyLookUpName', sa.String(length=255), nullable=False),
    sa.Column('constantsPropertyLookUpLink', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsPropertyLookUpID')
    )
    op.create_table('ConstantsEntitySubSource',
    sa.Column('constantsEntitySubSourceID', sa.UUID(), nullable=False),
    sa.Column('constantsEntitySubSourceName', sa.String(length=255), nullable=False),
    sa.Column('constantsEntitySourceID', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['constantsEntitySourceID'], ['ConstantsEntitySource.constantsEntitySourceID'], ),
    sa.PrimaryKeyConstraint('constantsEntitySubSourceID')
    )
    op.add_column('Entity', sa.Column('entityNotes', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('EntityCall', sa.Column('entityCallCallerID', sa.UUID(), nullable=True))
    op.add_column('EntityCall', sa.Column('entityCallNotes', sa.String(length=255), nullable=False, server_default=''))
    op.create_foreign_key(None, 'EntityCall', 'EmployeeMaster', ['entityCallCallerID'], ['employeeID'])
    op.drop_column('EntityCall', 'entityCallCaller')
    op.add_column('EntityPhone', sa.Column('entityPhoneID', sa.UUID(), nullable=False))
    op.add_column('EntityPhone', sa.Column('entityPhoneNumber', sa.String(length=255), nullable=False))
    op.add_column('EntityPhone', sa.Column('constantsPhoneTypeID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'EntityPhone', 'ConstantsPhoneType', ['constantsPhoneTypeID'], ['constantsPhoneTypeID'])
    op.drop_column('EntityPhone', 'phoneID')
    op.drop_column('EntityPhone', 'phoneType')
    op.drop_column('EntityPhone', 'phone')
    op.add_column('EntityProperty', sa.Column('entityPropertyNotes', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EntityProperty', 'entityPropertyNotes')
    op.add_column('EntityPhone', sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EntityPhone', sa.Column('phoneType', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EntityPhone', sa.Column('phoneID', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EntityPhone', type_='foreignkey')
    op.drop_column('EntityPhone', 'constantsPhoneTypeID')
    op.drop_column('EntityPhone', 'entityPhoneNumber')
    op.drop_column('EntityPhone', 'entityPhoneID')
    op.add_column('EntityCall', sa.Column('entityCallCaller', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EntityCall', type_='foreignkey')
    op.drop_column('EntityCall', 'entityCallNotes')
    op.drop_column('EntityCall', 'entityCallCallerID')
    op.drop_column('Entity', 'entityNotes')
    op.drop_table('ConstantsEntitySubSource')
    op.drop_table('ConstantsPropertyLookUp')
    op.drop_table('ConstantsPhoneType')
    op.drop_table('ConstantsEntitySource')
    op.drop_table('ConstantsEntityPropertyStructure')
    op.drop_table('ConstantsEntityMaritalStatus')
    op.drop_table('ConstantsEntityEmploymentStatus')
    op.drop_table('ConstantsEntityCallType')
    op.drop_table('ConstantsEntityCallResult')
    # ### end Alembic commands ###
