"""SalesJob table deleted

Revision ID: bd6f4e0e81d1
Revises: c1a488c2de38
Create Date: 2024-12-13 11:38:37.871765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd6f4e0e81d1'
down_revision: Union[str, None] = 'c1a488c2de38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CommissionReport_salesJobID_fkey', 'CommissionReport', type_='foreignkey')
    op.drop_column('CommissionReport', 'salesJobID')
    op.drop_constraint('ContractLineItem_salesJobID_fkey', 'ContractLineItem', type_='foreignkey')
    op.drop_column('ContractLineItem', 'salesJobID')
    op.drop_constraint('EmployeePayrollBonus_salesJobID_fkey', 'EmployeePayrollBonus', type_='foreignkey')
    op.drop_column('EmployeePayrollBonus', 'salesJobID')
    op.drop_constraint('SalesJobAddendum_salesJobID_fkey', 'SalesJobAddendum', type_='foreignkey')
    op.drop_column('SalesJobAddendum', 'salesJobID')
    op.drop_constraint('SalesJobCommissions_salesJobID_fkey', 'SalesJobCommissions', type_='foreignkey')
    op.drop_column('SalesJobCommissions', 'salesJobID')
    op.drop_constraint('SalesJobCost_salesJobID_fkey', 'SalesJobCost', type_='foreignkey')
    op.drop_column('SalesJobCost', 'salesJobID')
    op.drop_constraint('SalesJobDocuments_salesJobID_fkey', 'SalesJobDocuments', type_='foreignkey')
    op.drop_column('SalesJobDocuments', 'salesJobID')
    op.drop_constraint('SalesJobFinancing_salesJobID_fkey', 'SalesJobFinancing', type_='foreignkey')
    op.drop_column('SalesJobFinancing', 'salesJobID')
    op.drop_constraint('SalesJobMaterialsOrdered_salesJobID_fkey', 'SalesJobMaterialsOrdered', type_='foreignkey')
    op.drop_column('SalesJobMaterialsOrdered', 'salesJobID')
    op.drop_constraint('SalesJobMilestoneDate_salesJobID_fkey', 'SalesJobMilestoneDate', type_='foreignkey')
    op.drop_column('SalesJobMilestoneDate', 'salesJobID')
    op.drop_constraint('SalesJobNotes_salesJobID_fkey', 'SalesJobNotes', type_='foreignkey')
    op.drop_column('SalesJobNotes', 'salesJobID')
    op.drop_constraint('SalesJobPayment_salesJobID_fkey', 'SalesJobPayment', type_='foreignkey')
    op.drop_column('SalesJobPayment', 'salesJobID')
    op.drop_constraint('SalesJobPermits_salesJobID_fkey', 'SalesJobPermits', type_='foreignkey')
    op.drop_column('SalesJobPermits', 'salesJobID')
    op.drop_constraint('SalesJobServiceTicket_salesJobID_fkey', 'SalesJobServiceTicket', type_='foreignkey')
    op.drop_column('SalesJobServiceTicket', 'salesJobID')
    op.drop_table('SalesJob')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SalesJobServiceTicket', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobServiceTicket_salesJobID_fkey', 'SalesJobServiceTicket', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobPermits', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobPermits_salesJobID_fkey', 'SalesJobPermits', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobPayment', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobPayment_salesJobID_fkey', 'SalesJobPayment', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobNotes', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobNotes_salesJobID_fkey', 'SalesJobNotes', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobMilestoneDate', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobMilestoneDate_salesJobID_fkey', 'SalesJobMilestoneDate', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobMaterialsOrdered', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobMaterialsOrdered_salesJobID_fkey', 'SalesJobMaterialsOrdered', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobFinancing', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobFinancing_salesJobID_fkey', 'SalesJobFinancing', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobDocuments', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobDocuments_salesJobID_fkey', 'SalesJobDocuments', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobCost', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobCost_salesJobID_fkey', 'SalesJobCost', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobCommissions', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobCommissions_salesJobID_fkey', 'SalesJobCommissions', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('SalesJobAddendum', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('SalesJobAddendum_salesJobID_fkey', 'SalesJobAddendum', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('EmployeePayrollBonus', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('EmployeePayrollBonus_salesJobID_fkey', 'EmployeePayrollBonus', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('ContractLineItem', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('ContractLineItem_salesJobID_fkey', 'ContractLineItem', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.add_column('CommissionReport', sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('CommissionReport_salesJobID_fkey', 'CommissionReport', 'SalesJob', ['salesJobID'], ['salesJobID'])
    op.create_table('SalesJob',
    sa.Column('salesJobID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entityPropertyID', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('salesJobNumber', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobContractDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('salesJobStartDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('salesJobCompleteDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('salesJobGrossAmount', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobLeadRequirement', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('salesJobLastPriceOfferedAmount', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobFinanceOption', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobNotes', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('salesJobQualityControlled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('salesJobVoucherSentDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('salesJobArchitectureApplicationNeeded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('salesJobDispositionID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salesJobMeasuredByID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salesJobSalesPersonID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salesJobProjectManagerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salesJobSubContractorID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entityPropertyID'], ['EntityProperty.entityPropertyID'], name='SalesJob_entityPropertyID_fkey'),
    sa.ForeignKeyConstraint(['salesJobDispositionID'], ['ConstantsSalesJobDispositon.constantsSalesJobDispositonID'], name='SalesJob_salesJobDispositionID_fkey'),
    sa.ForeignKeyConstraint(['salesJobMeasuredByID'], ['EmployeeMaster.employeeID'], name='SalesJob_salesJobMeasuredByID_fkey'),
    sa.ForeignKeyConstraint(['salesJobProjectManagerID'], ['EmployeeMaster.employeeID'], name='SalesJob_salesJobProjectManagerID_fkey'),
    sa.ForeignKeyConstraint(['salesJobSalesPersonID'], ['EmployeeMaster.employeeID'], name='SalesJob_salesJobSalesPersonID_fkey'),
    sa.ForeignKeyConstraint(['salesJobSubContractorID'], ['SubContractor.subContractorID'], name='SalesJob_salesJobSubContractorID_fkey'),
    sa.PrimaryKeyConstraint('salesJobID', name='SalesJob_pkey')
    )
    # ### end Alembic commands ###
