"""subContactor and Installer Pk is changed to integer

Revision ID: c1a488c2de38
Revises: 8038c4c3103a
Create Date: 2024-12-12 11:26:25.353862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1a488c2de38'
down_revision: Union[str, None] = '8038c4c3103a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SubContractor',
    sa.Column('subContractorID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subContractorMarketID', sa.Integer(), nullable=True),
    sa.Column('subContractorCompanyName', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyAddressLine1', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyAddressLine2', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyCity', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyState', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyZipCode', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyPhone', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyEmail', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyLicenseNumber', sa.String(length=255), nullable=False),
    sa.Column('subContractorOwnerFirsttName', sa.String(length=255), nullable=False),
    sa.Column('subContractorOwnerLastName', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyOwnerPhone', sa.String(length=255), nullable=False),
    sa.Column('subContractorCompanyOwnerEmail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subContractorMarketID'], ['ConstantsMarketType.constantsMarketID'], ),
    sa.PrimaryKeyConstraint('subContractorID')
    )
    op.create_table('SubContractorInstaller',
    sa.Column('subContractorInstallerID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subContractorID', sa.Integer(), nullable=True),
    sa.Column('subContractorInstallerFirstName', sa.String(length=255), nullable=False),
    sa.Column('subContractorInstallerLastName', sa.String(length=255), nullable=False),
    sa.Column('subContractorInstallerPhone', sa.String(length=255), nullable=False),
    sa.Column('subContractorInstallerEmail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subContractorID'], ['SubContractor.subContractorID'], ),
    sa.PrimaryKeyConstraint('subContractorInstallerID')
    )
    op.add_column('SalesJob', sa.Column('salesJobSubContractorID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJob', 'SubContractor', ['salesJobSubContractorID'], ['subContractorID'])
    op.add_column('SalesJobServiceTicket', sa.Column('salesJobServiceTicketInstallerID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJobServiceTicket', 'SubContractor', ['salesJobServiceTicketInstallerID'], ['subContractorID'])
    op.add_column('SubContractorInstaller', sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='statusenum'), nullable=False))
    op.add_column('SubContractor', sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='statusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SalesJobServiceTicket', type_='foreignkey')
    op.drop_column('SalesJobServiceTicket', 'salesJobServiceTicketInstallerID')
    op.drop_constraint(None, 'SalesJob', type_='foreignkey')
    op.drop_column('SalesJob', 'salesJobSubContractorID')
    op.drop_table('SubContractorInstaller')
    op.drop_table('SubContractor')
    # ### end Alembic commands ###
