"""constant market type added in sub contractor

Revision ID: c1db3e046b2d
Revises: 91a3cdbee22b
Create Date: 2024-11-26 18:29:29.794594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1db3e046b2d'
down_revision: Union[str, None] = '91a3cdbee22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SubContractor', sa.Column('constantsMarketID', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'SubContractor', 'ConstantsMarketType', ['constantsMarketID'], ['constantsMarketID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SubContractor', type_='foreignkey')
    op.drop_column('SubContractor', 'constantsMarketID')
    # ### end Alembic commands ###
