"""commission_report model updated

Revision ID: d5bc0134203c
Revises: f0d70ab6a3fb
Create Date: 2024-11-21 21:49:02.288981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bc0134203c'
down_revision: Union[str, None] = 'f0d70ab6a3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CommissionReport', 'commissionReportCustomerEmail2',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('CommissionReport', 'commissionReportCustomerEmail3',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('CommissionReport', 'commissionReportCustomerAddressLine2',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('CommissionReport', 'commissionReportCustomerPhone2',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('CommissionReport', 'commissionReportNotes',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CommissionReport', 'commissionReportNotes',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('CommissionReport', 'commissionReportCustomerPhone2',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('CommissionReport', 'commissionReportCustomerAddressLine2',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('CommissionReport', 'commissionReportCustomerEmail3',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('CommissionReport', 'commissionReportCustomerEmail2',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    # ### end Alembic commands ###
