"""salesPersonAvailability and slots added

Revision ID: d7cc55fd91e4
Revises: c1db3e046b2d
Create Date: 2024-11-27 13:08:17.049387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7cc55fd91e4'
down_revision: Union[str, None] = 'c1db3e046b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SalesPersonAvailabilitySlots',
    sa.Column('salesPersonAvailabilitySlotsID', sa.UUID(), nullable=False),
    sa.Column('salesPersonAvailabilitySlotsDate', sa.DateTime(), nullable=False),
    sa.Column('salesPersonAvailabilitySlotsIsMorningAvailable', sa.Boolean(), nullable=False),
    sa.Column('salesPersonAvailabilitySlotsIsAfternoonAvailable', sa.Boolean(), nullable=False),
    sa.Column('salesPersonAvailabilitySlotsIsEveningAvailable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('salesPersonAvailabilitySlotsID')
    )
    op.create_table('SalesPersonAvailability',
    sa.Column('salesPersonAvailabilityID', sa.UUID(), nullable=False),
    sa.Column('salesPersonID', sa.UUID(), nullable=True),
    sa.Column('salesPersonAvailabilitySlotsID', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['salesPersonAvailabilitySlotsID'], ['SalesPersonAvailabilitySlots.salesPersonAvailabilitySlotsID'], ),
    sa.ForeignKeyConstraint(['salesPersonID'], ['EmployeeMaster.employeeID'], ),
    sa.PrimaryKeyConstraint('salesPersonAvailabilityID')
    )
    op.add_column('EntityCallback', sa.Column('entityCallbackIsComplete', sa.Boolean(), nullable=True))
    op.drop_column('EntityCallback', 'entityCallbackComplete')
    op.alter_column('SalesJobAddendum', 'salesJobAddendumCustomerEmail2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('SalesJobAddendum', 'salesJobAddendumCustomerEmail3',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('SalesJobAddendum', 'salesJobAddendumCustomerAddressLine2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('SalesJobAddendum', 'salesJobAddendumCustomerPhone2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('SubContractor', sa.Column('subContractorMarketID', sa.UUID(), nullable=True))
    op.drop_constraint('SubContractor_constantsMarketID_fkey', 'SubContractor', type_='foreignkey')
    op.create_foreign_key(None, 'SubContractor', 'ConstantsMarketType', ['subContractorMarketID'], ['constantsMarketID'])
    op.drop_column('SubContractor', 'constantsMarketID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SubContractor', sa.Column('constantsMarketID', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'SubContractor', type_='foreignkey')
    op.create_foreign_key('SubContractor_constantsMarketID_fkey', 'SubContractor', 'ConstantsMarketType', ['constantsMarketID'], ['constantsMarketID'])
    op.drop_column('SubContractor', 'subContractorMarketID')
    op.alter_column('SalesJobAddendum', 'salesJobAddendumCustomerPhone2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('SalesJobAddendum', 'salesJobAddendumCustomerAddressLine2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('SalesJobAddendum', 'salesJobAddendumCustomerEmail3',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('SalesJobAddendum', 'salesJobAddendumCustomerEmail2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('EntityCallback', sa.Column('entityCallbackComplete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('EntityCallback', 'entityCallbackIsComplete')
    op.drop_table('SalesPersonAvailability')
    op.drop_table('SalesPersonAvailabilitySlots')
    # ### end Alembic commands ###
