"""EmployeeMaster table created and relation added

Revision ID: db0874d7e2f6
Revises: 6e67e9eb8492
Create Date: 2024-12-10 12:32:57.110910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0874d7e2f6'
down_revision: Union[str, None] = '6e67e9eb8492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmployeeMaster',
    sa.Column('employeeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employeeBadgeID', sa.Integer(), nullable=False),
    sa.Column('employeeFirstName', sa.String(length=255), nullable=False),
    sa.Column('employeeLastName', sa.String(length=255), nullable=False),
    sa.Column('employeeHireDate', sa.DateTime(), nullable=False),
    sa.Column('employeeTerminationDate', sa.DateTime(), nullable=False),
    sa.Column('employeeIsActive', sa.Boolean(), nullable=False),
    sa.Column('employeeUserName', sa.String(length=255), nullable=False),
    sa.Column('employeePassword', sa.String(length=255), nullable=False),
    sa.Column('employeeEmail', sa.String(length=255), nullable=True),
    sa.Column('employeeTypeID', sa.Integer(), nullable=True),
    sa.Column('employeePayTypeID', sa.Integer(), nullable=True),
    sa.Column('employeeTitle', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeePayTypeID'], ['ConstantsEmployeePayType.constantsEmployeePayTypeID'], ),
    sa.ForeignKeyConstraint(['employeeTypeID'], ['ConstantsEmployeeType.constantsEmployeeTypeID'], ),
    sa.PrimaryKeyConstraint('employeeID')
    )
    op.add_column('CommissionReport', sa.Column('commissionReportDesignConsultanID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'CommissionReport', 'EmployeeMaster', ['commissionReportDesignConsultanID'], ['employeeID'])
    op.add_column('Entity', sa.Column('entityInboundRecordLockedByID', sa.Integer(), nullable=True))
    op.add_column('Entity', sa.Column('entityAssignedTo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Entity', 'EmployeeMaster', ['entityAssignedTo'], ['employeeID'])
    op.create_foreign_key(None, 'Entity', 'EmployeeMaster', ['entityInboundRecordLockedByID'], ['employeeID'])
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsSalesRep1', sa.Integer(), nullable=True))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsSalesRep2', sa.Integer(), nullable=True))
    op.add_column('EntityAppointments', sa.Column('entityAppointmentsLeadSetterID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'EntityAppointments', 'EmployeeMaster', ['entityAppointmentsSalesRep2'], ['employeeID'])
    op.create_foreign_key(None, 'EntityAppointments', 'EmployeeMaster', ['entityAppointmentsLeadSetterID'], ['employeeID'])
    op.create_foreign_key(None, 'EntityAppointments', 'EmployeeMaster', ['entityAppointmentsSalesRep1'], ['employeeID'])
    op.add_column('EntityCall', sa.Column('entityCallCallerID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'EntityCall', 'EmployeeMaster', ['entityCallCallerID'], ['employeeID'])
    op.add_column('EntityCallback', sa.Column('entityCallbackAssignedTo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'EntityCallback', 'EmployeeMaster', ['entityCallbackAssignedTo'], ['employeeID'])
    op.add_column('SalesJob', sa.Column('salesJobMeasuredByID', sa.Integer(), nullable=True))
    op.add_column('SalesJob', sa.Column('salesJobSalesPersonID', sa.Integer(), nullable=True))
    op.add_column('SalesJob', sa.Column('salesJobProjectManagerID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJob', 'EmployeeMaster', ['salesJobSalesPersonID'], ['employeeID'])
    op.create_foreign_key(None, 'SalesJob', 'EmployeeMaster', ['salesJobMeasuredByID'], ['employeeID'])
    op.create_foreign_key(None, 'SalesJob', 'EmployeeMaster', ['salesJobProjectManagerID'], ['employeeID'])
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumDesignConsultantID', sa.Integer(), nullable=True))
    op.add_column('SalesJobAddendum', sa.Column('salesJobAddendumProjectManagerID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJobAddendum', 'EmployeeMaster', ['salesJobAddendumProjectManagerID'], ['employeeID'])
    op.create_foreign_key(None, 'SalesJobAddendum', 'EmployeeMaster', ['salesJobAddendumDesignConsultantID'], ['employeeID'])
    op.add_column('SalesJobDocumentCategoryDocuments', sa.Column('salesJobDocumentCategoryDocumentsUploadedByID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJobDocumentCategoryDocuments', 'EmployeeMaster', ['salesJobDocumentCategoryDocumentsUploadedByID'], ['employeeID'])
    op.add_column('SalesJobNotes', sa.Column('salesJobNotesEnteredOnUserID', sa.Integer(), nullable=True))
    op.add_column('SalesJobNotes', sa.Column('salesJobNotesNotifyToID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJobNotes', 'EmployeeMaster', ['salesJobNotesEnteredOnUserID'], ['employeeID'])
    op.create_foreign_key(None, 'SalesJobNotes', 'EmployeeMaster', ['salesJobNotesNotifyToID'], ['employeeID'])
    op.add_column('SalesJobPayment', sa.Column('salesJobPaymentEnteredByID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJobPayment', 'EmployeeMaster', ['salesJobPaymentEnteredByID'], ['employeeID'])
    op.add_column('SalesJobPermits', sa.Column('salesJobPermitsAssignedToID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJobPermits', 'EmployeeMaster', ['salesJobPermitsAssignedToID'], ['employeeID'])
    op.add_column('SalesJobServiceTicket', sa.Column('salesJobServiceTicketAssignToID', sa.Integer(), nullable=True))
    op.add_column('SalesJobServiceTicket', sa.Column('salesJobServiceTicketEnteredByID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJobServiceTicket', 'EmployeeMaster', ['salesJobServiceTicketEnteredByID'], ['employeeID'])
    op.create_foreign_key(None, 'SalesJobServiceTicket', 'EmployeeMaster', ['salesJobServiceTicketAssignToID'], ['employeeID'])
    op.add_column('SalesJobServiceTicketLogs', sa.Column('employeeID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesJobServiceTicketLogs', 'EmployeeMaster', ['employeeID'], ['employeeID'])
    op.add_column('SalesPersonAvailability', sa.Column('salesPersonID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SalesPersonAvailability', 'EmployeeMaster', ['salesPersonID'], ['employeeID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SalesPersonAvailability', type_='foreignkey')
    op.drop_column('SalesPersonAvailability', 'salesPersonID')
    op.drop_constraint(None, 'SalesJobServiceTicketLogs', type_='foreignkey')
    op.drop_column('SalesJobServiceTicketLogs', 'employeeID')
    op.drop_constraint(None, 'SalesJobServiceTicket', type_='foreignkey')
    op.drop_constraint(None, 'SalesJobServiceTicket', type_='foreignkey')
    op.drop_column('SalesJobServiceTicket', 'salesJobServiceTicketEnteredByID')
    op.drop_column('SalesJobServiceTicket', 'salesJobServiceTicketAssignToID')
    op.drop_constraint(None, 'SalesJobPermits', type_='foreignkey')
    op.drop_column('SalesJobPermits', 'salesJobPermitsAssignedToID')
    op.drop_constraint(None, 'SalesJobPayment', type_='foreignkey')
    op.drop_column('SalesJobPayment', 'salesJobPaymentEnteredByID')
    op.drop_constraint(None, 'SalesJobNotes', type_='foreignkey')
    op.drop_constraint(None, 'SalesJobNotes', type_='foreignkey')
    op.drop_column('SalesJobNotes', 'salesJobNotesNotifyToID')
    op.drop_column('SalesJobNotes', 'salesJobNotesEnteredOnUserID')
    op.drop_constraint(None, 'SalesJobDocumentCategoryDocuments', type_='foreignkey')
    op.drop_column('SalesJobDocumentCategoryDocuments', 'salesJobDocumentCategoryDocumentsUploadedByID')
    op.drop_constraint(None, 'SalesJobAddendum', type_='foreignkey')
    op.drop_constraint(None, 'SalesJobAddendum', type_='foreignkey')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumProjectManagerID')
    op.drop_column('SalesJobAddendum', 'salesJobAddendumDesignConsultantID')
    op.drop_constraint(None, 'SalesJob', type_='foreignkey')
    op.drop_constraint(None, 'SalesJob', type_='foreignkey')
    op.drop_constraint(None, 'SalesJob', type_='foreignkey')
    op.drop_column('SalesJob', 'salesJobProjectManagerID')
    op.drop_column('SalesJob', 'salesJobSalesPersonID')
    op.drop_column('SalesJob', 'salesJobMeasuredByID')
    op.drop_constraint(None, 'EntityCallback', type_='foreignkey')
    op.drop_column('EntityCallback', 'entityCallbackAssignedTo')
    op.drop_constraint(None, 'EntityCall', type_='foreignkey')
    op.drop_column('EntityCall', 'entityCallCallerID')
    op.drop_constraint(None, 'EntityAppointments', type_='foreignkey')
    op.drop_constraint(None, 'EntityAppointments', type_='foreignkey')
    op.drop_constraint(None, 'EntityAppointments', type_='foreignkey')
    op.drop_column('EntityAppointments', 'entityAppointmentsLeadSetterID')
    op.drop_column('EntityAppointments', 'entityAppointmentsSalesRep2')
    op.drop_column('EntityAppointments', 'entityAppointmentsSalesRep1')
    op.drop_constraint(None, 'Entity', type_='foreignkey')
    op.drop_constraint(None, 'Entity', type_='foreignkey')
    op.drop_column('Entity', 'entityAssignedTo')
    op.drop_column('Entity', 'entityInboundRecordLockedByID')
    op.drop_constraint(None, 'CommissionReport', type_='foreignkey')
    op.drop_column('CommissionReport', 'commissionReportDesignConsultanID')
    op.drop_table('EmployeeMaster')
    # ### end Alembic commands ###
