"""new fields added in entity, entitypropertcontact

Revision ID: dcff47cb9c1f
Revises: f7ce9c3bf66d
Create Date: 2024-12-06 22:25:45.264452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcff47cb9c1f'
down_revision: Union[str, None] = 'f7ce9c3bf66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConstantsRelationType',
    sa.Column('constantsRelationTypeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constantsRelationTypeName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsRelationTypeID')
    )
    op.add_column('Entity', sa.Column('entityrIsTextPreferred', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('Entity', sa.Column('entityIsEmailPreferred', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('Entity', sa.Column('entityIsCallPreferred', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('EntityPropertyContact', sa.Column('entityPropertyContactRelationTypeID', sa.Integer(), nullable=True))
    op.add_column('EntityPropertyContact', sa.Column('entityrIsTextPreferred', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('EntityPropertyContact', sa.Column('entityIsEmailPreferred', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('EntityPropertyContact', sa.Column('entityIsCallPreferred', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('EntityPropertyContact', sa.Column('entityDNCWaiver', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.create_foreign_key(None, 'EntityPropertyContact', 'ConstantsRelationType', ['entityPropertyContactRelationTypeID'], ['constantsRelationTypeID'])
    op.drop_column('EntityPropertyContact', 'entityPropertyContactRelationType')
    op.add_column('EntitySecondaryContactDetails', sa.Column('entitySecondaryContactRelationshipTypeID', sa.Integer(), nullable=True))
    op.add_column('EntitySecondaryContactDetails', sa.Column('entityrIsTextPreferred', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('EntitySecondaryContactDetails', sa.Column('entityIsEmailPreferred', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('EntitySecondaryContactDetails', sa.Column('entityIsCallPreferred', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('EntitySecondaryContactDetails', sa.Column('entityDNCWaiver', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.create_foreign_key(None, 'EntitySecondaryContactDetails', 'ConstantsRelationType', ['entitySecondaryContactRelationshipTypeID'], ['constantsRelationTypeID'])
    op.drop_column('EntitySecondaryContactDetails', 'entitySecondaryContactRelationshipType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EntitySecondaryContactDetails', sa.Column('entitySecondaryContactRelationshipType', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EntitySecondaryContactDetails', type_='foreignkey')
    op.drop_column('EntitySecondaryContactDetails', 'entityDNCWaiver')
    op.drop_column('EntitySecondaryContactDetails', 'entityIsCallPreferred')
    op.drop_column('EntitySecondaryContactDetails', 'entityIsEmailPreferred')
    op.drop_column('EntitySecondaryContactDetails', 'entityrIsTextPreferred')
    op.drop_column('EntitySecondaryContactDetails', 'entitySecondaryContactRelationshipTypeID')
    op.add_column('EntityPropertyContact', sa.Column('entityPropertyContactRelationType', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EntityPropertyContact', type_='foreignkey')
    op.drop_column('EntityPropertyContact', 'entityDNCWaiver')
    op.drop_column('EntityPropertyContact', 'entityIsCallPreferred')
    op.drop_column('EntityPropertyContact', 'entityIsEmailPreferred')
    op.drop_column('EntityPropertyContact', 'entityrIsTextPreferred')
    op.drop_column('EntityPropertyContact', 'entityPropertyContactRelationTypeID')
    op.drop_column('Entity', 'entityIsCallPreferred')
    op.drop_column('Entity', 'entityIsEmailPreferred')
    op.drop_column('Entity', 'entityrIsTextPreferred')
    op.drop_table('ConstantsRelationType')
    # ### end Alembic commands ###
