"""UserId added in employeemaster

Revision ID: f0b2af430be4
Revises: db0874d7e2f6
Create Date: 2024-12-10 13:17:55.240856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b2af430be4'
down_revision: Union[str, None] = 'db0874d7e2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmployeeMaster', sa.Column('userID', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'EmployeeMaster', ['userID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EmployeeMaster', type_='unique')
    op.drop_column('EmployeeMaster', 'userID')
    # ### end Alembic commands ###
