"""EmployeeMaster updated and ConstantsEmployeeType, ConstantsEmployeePayType created

Revision ID: f0d70ab6a3fb
Revises: 6e987c995bd0
Create Date: 2024-11-20 15:20:52.905138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0d70ab6a3fb'
down_revision: Union[str, None] = '6e987c995bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConstantsEmployeePayType',
    sa.Column('constantsEmployeePayTypeID', sa.UUID(), nullable=False),
    sa.Column('constantsEmployeePayTypeName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEmployeePayTypeID')
    )
    op.create_table('ConstantsEmployeeType',
    sa.Column('constantsEmployeeTypeID', sa.UUID(), nullable=False),
    sa.Column('constantsEmployeeTypeName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('constantsEmployeeTypeID')
    )
    op.add_column('SamMultiLambdaAppBaseTable', sa.Column('baseInboundRecordNumber', sa.Integer(), nullable=False))
    op.add_column('SamMultiLambdaAppBaseTable', sa.Column('baseCustomerRecordNumber', sa.Integer(), nullable=False))
    op.add_column('EmployeeMaster', sa.Column('employeeIsActive', sa.Boolean(), nullable=False))
    op.add_column('EmployeeMaster', sa.Column('employeeTypeID', sa.UUID(), nullable=True))
    op.add_column('EmployeeMaster', sa.Column('employeePayTypeID', sa.UUID(), nullable=True))
    op.add_column('EmployeeMaster', sa.Column('employeeTitle', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'EmployeeMaster', 'ConstantsEmployeePayType', ['employeePayTypeID'], ['constantsEmployeePayTypeID'])
    op.create_foreign_key(None, 'EmployeeMaster', 'ConstantsEmployeeType', ['employeeTypeID'], ['constantsEmployeeTypeID'])
    op.drop_column('EmployeeMaster', 'employeeActive')
    op.drop_column('EmployeeMaster', 'employeeChangeInFullTimeSalary')
    op.drop_column('EmployeeMaster', 'employeePayType')
    op.drop_column('EmployeeMaster', 'employeeStartFullTimeSalary')
    op.drop_column('EmployeeMaster', 'employeeChangeInFullTimeSalaryEffectiveDate')
    op.drop_column('EmployeeMaster', 'employeeType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmployeeMaster', sa.Column('employeeType', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EmployeeMaster', sa.Column('employeeChangeInFullTimeSalaryEffectiveDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('EmployeeMaster', sa.Column('employeeStartFullTimeSalary', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EmployeeMaster', sa.Column('employeePayType', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EmployeeMaster', sa.Column('employeeChangeInFullTimeSalary', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('EmployeeMaster', sa.Column('employeeActive', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EmployeeMaster', type_='foreignkey')
    op.drop_constraint(None, 'EmployeeMaster', type_='foreignkey')
    op.drop_column('EmployeeMaster', 'employeeTitle')
    op.drop_column('EmployeeMaster', 'employeePayTypeID')
    op.drop_column('EmployeeMaster', 'employeeTypeID')
    op.drop_column('EmployeeMaster', 'employeeIsActive')
    op.drop_column('BellemarBaseTable', 'baseCustomerRecordNumber')
    op.drop_column('BellemarBaseTable', 'baseInboundRecordNumber')
    op.drop_table('ConstantsEmployeeType')
    op.drop_table('ConstantsEmployeePayType')
    # ### end Alembic commands ###
