"""entity and propertyContact upgrade and states table created

Revision ID: f7ce9c3bf66d
Revises: 534e13a3f3d6
Create Date: 2024-12-06 16:39:57.265233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ce9c3bf66d'
down_revision: Union[str, None] = '534e13a3f3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConsantsUSAStates',
    sa.Column('consantsUSAStatesID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consantsUSAStatesName', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('consantsUSAStatesID')
    )
    op.add_column('Entity', sa.Column('entityIniitialName', sa.String(length=255), nullable=True))
    op.add_column('Entity', sa.Column('entityMartialStatus', sa.String(length=255), nullable=True))
    op.add_column('Entity', sa.Column('entityEmployment', sa.String(length=255), nullable=True))
    op.add_column('Entity', sa.Column('entityMarket', sa.String(length=255), nullable=True))
    op.add_column('Entity', sa.Column('entityAssignedTo', sa.UUID(), nullable=True))
    op.add_column('Entity', sa.Column('entityContactPreference', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'Entity', 'EmployeeMaster', ['entityAssignedTo'], ['employeeID'])
    op.add_column('EntityPropertyContact', sa.Column('entityPropertyMartialStatus', sa.String(length=255), nullable=False))
    op.add_column('EntityPropertyContact', sa.Column('entityPropertyEmployment', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EntityPropertyContact', 'entityPropertyEmployment')
    op.drop_column('EntityPropertyContact', 'entityPropertyMartialStatus')
    op.drop_constraint(None, 'Entity', type_='foreignkey')
    op.drop_column('Entity', 'entityContactPreference')
    op.drop_column('Entity', 'entityAssignedTo')
    op.drop_column('Entity', 'entityMarket')
    op.drop_column('Entity', 'entityEmployment')
    op.drop_column('Entity', 'entityMartialStatus')
    op.drop_column('Entity', 'entityIniitialName')
    op.drop_table('ConsantsUSAStates')
    # ### end Alembic commands ###
