"""status added in entityAppointment

Revision ID: fda3e6bb359a
Revises: a38a72254696
Create Date: 2024-12-16 13:55:58.719183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fda3e6bb359a'
down_revision: Union[str, None] = 'a38a72254696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('EntityAppointments', sa.Column('status', postgresql.ENUM('Completed', 'On Hold', 'In Progress', name='appointmentenum'), nullable=False, server_default='On Hold'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EntityAppointments', 'status')
    # ### end Alembic commands ###
