from handlers import getConstantsMarketType, getConstantsProductType, createConstantsMarketType, createConstantsProductType, updateConstantsMarketType, updateConstantsProductType, deleteConstantsMarketType, deleteConstantsProductType, getConstantsEmployeeType, createConstantsEmployeeType, updateConstantsEmployeeType, deleteConstantsEmployeeType, getConstantsEmployeePayType, createConstantsEmployeePayType, updateConstantsEmployeePayType, deleteConstantsEmployeePayType, getAllConstantsData,getConstantsPhoneType, createConstantsPhoneType, updateConstantsPhoneType, deleteConstantsPhoneType, getConstantsEntityEmploymentStatus, createConstantsEntityEmploymentStatus, updateConstantsEntityEmploymentStatus, deleteConstantsEntityEmploymentStatus, getConstantsAppointmentDisposition, createConstantsAppointmentDisposition, updateConstantsAppointmentDisposition, deleteConstantsAppointmentDisposition, getConstantsEntityMaritalStatus, createConstantsEntityMaritalStatus, updateConstantsEntityMaritalStatus, deleteConstantsEntityMaritalStatus, getConstantsEntityPropertyStructure, createConstantsEntityPropertyStructure, updateConstantsEntityPropertyStructure, deleteConstantsEntityPropertyStructure, getConstantsEntitySource, createConstantsEntitySource, updateConstantsEntitySource, deleteConstantsEntitySource, getConstantsEntitySubSource, createConstantsEntitySubSource, updateConstantsEntitySubSource, deleteConstantsEntitySubSource, getConstantsPropertyLookUp, createConstantsPropertyLookUp, updateConstantsPropertyLookUp, deleteConstantsPropertyLookUp, getConstantsRelationType, createConstantsRelationType, updateConstantsRelationType, deleteConstantsRelationType, getConstantsSalesJobDispositon, createConstantsSalesJobDispositon, updateConstantsSalesJobDispositon,deleteConstantsEntityCallType, getConstantsEntityCallType, createConstantsEntityCallType, updateConstantsEntityCallType, deleteConstantsSalesJobDispositon, getConstantsUSAStates, createConstantsUSAStates, updateConstantsUSAStates, deleteConstantsUSAStates,getConstantsEntityCallResult, createConstantsEntityCallResult, updateConstantsEntityCallResult, deleteConstantsEntityCallResult, getConstantsDeliveryWarehouse, createConstantsDeliveryWarehouse, updateConstantsDeliveryWarehouse, deleteConstantsDeliveryWarehouse, getConstantsMaterialsVendor, createConstantsMaterialsVendor, updateConstantsMaterialsVendor, deleteConstantsMaterialsVendor, getConstantsVoucherType, createConstantsVoucherType, updateConstantsVoucherType, deleteConstantsVoucherType
UUID_REGEX_PATTERN = "[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}"
INTEGER_REGEX_PATTERN = "[0-9]{0,}"
available_methods = [
    "GET",
    "POST",
    "PATCH",
    "DELETE",
]

routes = {
    "GET": {
        f"/constants-market-type/?(?P<constants_market_type_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsMarketType,
        f"/constants-product-type/?(?P<constants_product_type_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsProductType,
        f"/constants-employee-type/?(?P<constants_employee_type_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsEmployeeType,
        f"/constants-employee-pay-type/?(?P<employee_pay_type_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsEmployeePayType,
        "/all-constants" : getAllConstantsData,
        f"/constants-phone-type/?(?P<constants_phone_type_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsPhoneType,
        f"/constants-appointment-disposition/?(?P<constants_appointment_disposition_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsAppointmentDisposition,
        f"/constants-employment-status/?(?P<constants_employment_status_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsEntityEmploymentStatus,
        f"/constants-marital-status/?(?P<constants_marital_status_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsEntityMaritalStatus,
        f"/constants-entity-property-structure/?(?P<constants_entity_property_structure_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsEntityPropertyStructure,
        f"/constants-entity-source/?(?P<constants_entity_source_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsEntitySource,
        f"/constants-entity-sub-source/?(?P<constants_entity_sub_source_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsEntitySubSource,
        f"/constants-property-lookup/?(?P<constants_property_lookup_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsPropertyLookUp,
        f"/constants-usa-states/?(?P<constants_usa_states_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsUSAStates,   
        f"/constants-relation-type/?(?P<constants_relation_type_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsRelationType,  
        f"/constants-entity-call-type/?(?P<constants_entity_call_type_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsEntityCallType,
        f"/constants-sales-job-disposition/?(?P<constants_sales_job_disposition_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsSalesJobDispositon,
        f"/constants-entity-call-result/?(?P<constants_entity_call_result_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsEntityCallResult,
        f"/constants-delivery-warehouse/?(?P<constants_delivery_warehouse_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsDeliveryWarehouse,
        f"/constants-materials-vendor/?(?P<constants_materials_vendor_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsMaterialsVendor,
        f"/constants-voucher-type/?(?P<constants_voucher_type_id>{INTEGER_REGEX_PATTERN})?/?$": getConstantsVoucherType,

    },
    "POST": {
        "/constants-market-type" : createConstantsMarketType,
        "/constants-product-type" : createConstantsProductType,
        "/constants-employee-type": createConstantsEmployeeType,
        "/constants-employee-pay-type": createConstantsEmployeePayType,
        "/constants-phone-type" : createConstantsPhoneType,
        "/constants-appointment-disposition" : createConstantsAppointmentDisposition,
        "/constants-employment-status" : createConstantsEntityEmploymentStatus,
        "/constants-marital-status" : createConstantsEntityMaritalStatus,
        "/constants-entity-property-structure" : createConstantsEntityPropertyStructure,
        "/constants-entity-source" : createConstantsEntitySource,
        "/constants-entity-sub-source" : createConstantsEntitySubSource,
        "/constants-property-lookup" : createConstantsPropertyLookUp,
        "/constants-usa-states" : createConstantsUSAStates,
        "/constants-relation-type" : createConstantsRelationType,
        "/constants-entity-call-type" : createConstantsEntityCallType,   
        "/constants-sales-job-disposition" : createConstantsSalesJobDispositon,
        "/constants-entity-call-result" : createConstantsEntityCallResult, 
        "/constants-delivery-warehouse" : createConstantsDeliveryWarehouse, 
        "/constants-materials-vendor" : createConstantsMaterialsVendor,
        "/constants-voucher-type" : createConstantsVoucherType
    },
    "PATCH" : {
        "/constants-market-type" : updateConstantsMarketType,
        "/constants-product-type" : updateConstantsProductType,
        "/constants-employee-type": updateConstantsEmployeeType,
        "/constants-employee-pay-type": updateConstantsEmployeePayType, 
        "/constants-phone-type" : updateConstantsPhoneType,
        "/constants-appointment-disposition" : updateConstantsAppointmentDisposition,
        "/constants-employment-status" : updateConstantsEntityEmploymentStatus,
        "/constants-marital-status" : updateConstantsEntityMaritalStatus,
        "/constants-entity-property-structure" : updateConstantsEntityPropertyStructure,
        "/constants-entity-source" : updateConstantsEntitySource,
        "/constants-entity-sub-source" : updateConstantsEntitySubSource,
        "/constants-property-lookup" : updateConstantsPropertyLookUp,
        "/constants-usa-states" : updateConstantsUSAStates,
        "/constants-relation-type" : updateConstantsRelationType,
        "/constants-entity-call-type": updateConstantsEntityCallType, 
        "/constants-sales-job-disposition" : updateConstantsSalesJobDispositon,
        "/constants-entity-call-result" : updateConstantsEntityCallResult,
        "/constants-delivery-warehouse" : updateConstantsDeliveryWarehouse,
        "/constants-materials-vendor" : updateConstantsMaterialsVendor,
        "/constants-voucher-type" : updateConstantsVoucherType  

    },
    "DELETE" : {
        f"/constants-product-type/?(?P<constants_product_type_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsProductType,
        f"/constants-market-type/?(?P<constants_market_type_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsMarketType,
        f"/constants-employee-pay-type/?(?P<employee_pay_type_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsEmployeePayType,
        f"/constants-employee-type/?(?P<constants_employee_type_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsEmployeeType,
        f"/constants-phone-type/?(?P<constants_phone_type_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsPhoneType,
        f"/constants-appointment-disposition/?(?P<constants_appointment_disposition_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsAppointmentDisposition,
        f"/constants-employment-status/?(?P<constants_employment_status_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsEntityEmploymentStatus,
        f"/constants-marital-status/?(?P<constants_marital_status_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsEntityMaritalStatus,
        f"/constants-entity-property-structure/?(?P<constants_entity_property_structure_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsEntityPropertyStructure,
        f"/constants-entity-source/?(?P<constants_entity_source_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsEntitySource,
        f"/constants-entity-sub-source/?(?P<constants_entity_sub_source_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsEntitySubSource,
        f"/constants-property-lookup/?(?P<constants_property_lookup_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsPropertyLookUp,
        f"/constants-usa-states/?(?P<constants_usa_states_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsUSAStates,
        f"/constants-relation-type/?(?P<constants_relation_type_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsRelationType,
        f"/constants-employee-type/?(?P<constants_employee_type_id>{INTEGER_REGEX_PATTERN})?/?$" : deleteConstantsEntityCallType,   
        f"/constants-sales-job-disposition/?(?P<constants_sales_job_disposition_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsSalesJobDispositon,
        f"/constants-entity-call-result/?(?P<constants_entity_call_result_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsEntityCallResult,  
        f"/constants-delivery-warehouse/?(?P<constants_delivery_warehouse_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsDeliveryWarehouse,
        f"/constants-materials-vendor/?(?P<constants_materials_vendor_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsMaterialsVendor,
        f"/constants-voucher-type/?(?P<constants_voucher_type_id>{INTEGER_REGEX_PATTERN})?/?$": deleteConstantsVoucherType,

        
    }
}
